'use strict';
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..', '..');
const c = fs.readFileSync(path.join(root, 'nexus-v6.html'), 'utf8');
console.log('Lines:', c.split('\n').length);
console.log('Has DOCTYPE:', c.startsWith('<!DOCTYPE'));
console.log('Has </html>:', c.trimEnd().endsWith('</html>'));
console.log('Has login:', c.includes('id="login"'));
console.log('Has app:', c.includes('id="app"'));
console.log('Has automation:', c.includes('automation'));
console.log('Has flow-node:', c.includes('flow-node'));
console.log('Has cerebrum:', c.toLowerCase().includes('cerebrum'));
console.log('Has tr-quiz:', c.includes('tr-quiz'));
console.log('Has nav-group:', c.includes('nav-group'));
console.log('Has _initDatabase:', c.includes('_initDatabase'));
console.log('Has _initAutomation:', c.includes('_initAutomation'));
console.log('<script> open:', c.split('<script').length - 1);
console.log('</script> close:', c.split('</script>').length - 1);
console.log('Has doLogin:', c.includes('doLogin'));
console.log('Has ROLE_NAV:', c.includes('ROLE_NAV'));
