const fs = require('fs');
const path = require('path');
const out = path.join(__dirname, 'nexus-demo.html');
const lines = [];
const p = s => lines.push(s);

p('<!DOCTYPE html>');
p('<html lang="en">');
p('<head>');
p('<meta charset="UTF-8">');
p('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
p('<title>NEXUS v4 — Broadcast IP Platform Demo</title>');
p('<style>');
p('*{box-sizing:border-box;margin:0;padding:0}');
p('body{background:#0a0a0a;color:#e0e0e0;font-family:monospace;font-size:13px}');
p('nav{display:flex;background:#111;border-bottom:1px solid #222;padding:0 8px}');
p('nav button{padding:10px 18px;background:none;border:none;color:#888;cursor:pointer;font-family:monospace;font-size:13px;border-bottom:2px solid transparent}');
p('nav button.active{color:#0af;border-bottom-color:#0af}');
p('nav .logo{padding:10px 16px;color:#0af;font-weight:bold;font-size:15px;letter-spacing:2px;margin-right:8px}');
p('.view{display:none;padding:12px}');
p('.view.active{display:block}');
p('/* MOSAIC */');
p('.mv-grid{display:grid;gap:2px;background:#000}');
p('.mv-cell{aspect-ratio:16/9;position:relative;overflow:hidden;cursor:pointer;border:2px solid #333}');
p('.mv-cell.pgm{border-color:#f00}');
p('.mv-cell.pvw{border-color:#0f0}');
p('.mv-cell .bg{width:100%;height:100%;display:flex;align-items:center;justify-content:center}');
p('.mv-cell .lbl{position:absolute;bottom:0;left:0;right:0;background:rgba(0,0,0,.75);padding:2px 4px;font-size:10px;display:flex;justify-content:space-between}');
p('.mv-cell .tally-tag{font-weight:bold}');
p('.mv-cell.pgm .tally-tag{color:#f00}');
p('.mv-cell.pvw .tally-tag{color:#0f0}');
p('.layout-btns{display:flex;gap:4px;margin-bottom:8px;align-items:center}');
p('.layout-btns button{padding:3px 9px;background:#222;color:#aaa;border:1px solid #333;border-radius:2px;cursor:pointer;font-family:monospace;font-size:11px}');
p('.layout-btns button.active{background:#0af;color:#000}');
p('/* SWITCH */');
p('.bus-row{margin-bottom:8px}');
p('.bus-label{font-size:10px;margin-bottom:3px;font-weight:bold}');
p('.bus-label.pgm{color:#f44}');
p('.bus-label.pvw{color:#4f4}');
p('.bus-btns{display:flex;flex-wrap:wrap;gap:3px}');
p('.bus-btns button{padding:3px 7px;font-size:10px;font-family:monospace;border:1px solid #333;border-radius:2px;cursor:pointer;background:#1e1e1e;color:#777}');
p('.bus-btns button.pgm-active{background:#c00;color:#fff;border-color:#f00}');
p('.bus-btns button.pvw-active{background:#060;color:#fff;border-color:#0f0}');
p('.sw-controls{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-top:10px;padding:10px;background:#111;border-radius:4px}');
p('.btn-cut{padding:8px 28px;background:#c00;color:#fff;border:none;border-radius:3px;font-size:15px;font-weight:bold;cursor:pointer;font-family:monospace}');
p('.btn-cut:hover{background:#f00}');
p('.btn-auto{padding:8px 28px;background:#0af;color:#000;border:none;border-radius:3px;font-size:15px;font-weight:bold;cursor:pointer;font-family:monospace}');
p('.btn-auto:hover{background:#0cf}');
p('.trans-btns button{padding:3px 9px;font-size:11px;font-family:monospace;border:1px solid #333;border-radius:2px;cursor:pointer;background:#1e1e1e;color:#aaa}');
p('.trans-btns button.active{background:#0af;color:#000}');
p('.progress-bar{height:6px;background:#222;border-radius:3px;margin-top:6px;overflow:hidden;width:200px}');
p('.progress-fill{height:100%;background:#0af;width:0%;transition:width 0.05s linear}');
p('/* SCOPE */');
p('.scope-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}');
p('.scope-panel{background:#111;border:1px solid #222;border-radius:4px;padding:8px}');
p('.scope-panel h3{font-size:11px;color:#888;margin-bottom:6px;text-transform:uppercase}');
p('.scope-panel canvas{width:100%;display:block;background:#000;border-radius:2px}');
p('/* SYNC */');
p('.ptp-card{background:#111;border:1px solid #222;border-radius:4px;padding:12px;margin-bottom:8px}');
p('.ptp-offset{font-size:36px;font-weight:bold;color:#0af}');
p('.ptp-offset span{font-size:14px;color:#888}');
p('.ptp-meta{display:flex;gap:24px;margin-top:8px;font-size:11px;color:#888}');
p('.ptp-meta b{color:#ccc}');
p('.ptp-log{background:#0a0a0a;border:1px solid #1a1a1a;border-radius:3px;padding:8px;height:140px;overflow-y:auto;font-size:10px;color:#4a4}');
p('.ptp-log .entry{margin-bottom:2px}');
p('.ptp-log .ts{color:#555;margin-right:6px}');
p('/* CONNECT */');
p('.nmos-list{display:flex;flex-direction:column;gap:6px}');
p('.nmos-device{display:flex;align-items:center;justify-content:space-between;background:#111;border:1px solid #222;border-radius:4px;padding:8px 12px}');
p('.nmos-device .info{display:flex;flex-direction:column;gap:2px}');
p('.nmos-device .name{color:#ccc;font-size:12px}');
p('.nmos-device .meta{color:#555;font-size:10px}');
p('.nmos-device .dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:6px}');
p('.nmos-device .dot.on{background:#0f0}');
p('.nmos-device .dot.off{background:#555}');
p('.btn-connect{padding:4px 14px;font-size:11px;font-family:monospace;border:1px solid #0af;border-radius:2px;background:none;color:#0af;cursor:pointer}');
p('.btn-connect.connected{border-color:#f44;color:#f44}');
p('/* PRE-DEPLOY */');
p('.phase{background:#111;border:1px solid #222;border-radius:4px;padding:10px 14px;margin-bottom:8px}');
p('.phase h3{font-size:12px;color:#0af;margin-bottom:8px}');
p('.check-item{display:flex;align-items:center;gap:8px;margin-bottom:5px;font-size:11px;color:#aaa}');
p('.check-item input[type=checkbox]{accent-color:#0af;width:14px;height:14px;cursor:pointer}');
p('.check-item.done{color:#4f4}');
p('.go-banner{padding:12px 20px;border-radius:4px;font-size:16px;font-weight:bold;text-align:center;margin-top:10px;letter-spacing:2px}');
p('.go-banner.go{background:#0a2a0a;border:2px solid #0f0;color:#0f0}');
p('.go-banner.nogo{background:#2a0a0a;border:2px solid #f00;color:#f00}');
p('/* STATUS BAR */');
p('.statusbar{position:fixed;bottom:0;left:0;right:0;background:#111;border-top:1px solid #222;padding:4px 12px;display:flex;gap:20px;align-items:center;font-size:10px;color:#666;z-index:100}');
p('.statusbar .dot{width:7px;height:7px;border-radius:50%;display:inline-block;margin-right:4px}');
p('.statusbar .dot.green{background:#0f0}');
p('.statusbar .dot.red{background:#f00}');
p('.statusbar .dot.yellow{background:#fa0}');
p('.statusbar .dot.grey{background:#555}');
p('.statusbar .sep{color:#333}');
p('</style>');
p('</head>');
p('<body>');

p('<nav>');
p('  <div class="logo">NEXUS v4</div>');
p('  <button class="active" onclick="showView(\'mosaic\',this)">MOSAIC</button>');
p('  <button onclick="showView(\'switch\',this)">SWITCH</button>');
p('  <button onclick="showView(\'scope\',this)">SCOPE</button>');
p('  <button onclick="showView(\'sync\',this)">SYNC</button>');
p('  <button onclick="showView(\'connect\',this)">CONNECT</button>');
p('  <button onclick="showView(\'predeploy\',this)">PRE-DEPLOY</button>');
p('</nav>');
p('');
p('<!-- MOSAIC VIEW -->');
p('<div id="view-mosaic" class="view active">');
p('  <div class="layout-btns">');
p('    <span style="color:#666;margin-right:4px">LAYOUT:</span>');
p('    <button class="active" onclick="setLayout(1,1,this)">1×1</button>');
p('    <button onclick="setLayout(2,2,this)">2×2</button>');
p('    <button onclick="setLayout(3,3,this)">3×3</button>');
p('    <button onclick="setLayout(4,4,this)">4×4</button>');
p('    <button onclick="setLayout(2,4,this)">2×4</button>');
p('    <button onclick="setLayout(3,4,this)">3×4</button>');
p('  </div>');
p('  <div id="mv-grid" class="mv-grid"></div>');
p('</div>');
p('');
p('<!-- SWITCH VIEW -->');
p('<div id="view-switch" class="view">');
p('  <div class="bus-row">');
p('    <div class="bus-label pvw">PREVIEW BUS</div>');
p('    <div id="pvw-bus" class="bus-btns"></div>');
p('  </div>');
p('  <div class="bus-row">');
p('    <div class="bus-label pgm">PROGRAM BUS</div>');
p('    <div id="pgm-bus" class="bus-btns"></div>');
p('  </div>');
p('  <div class="sw-controls">');
p('    <div>');
p('      <div style="font-size:10px;color:#666;margin-bottom:4px">TRANSITION</div>');
p('      <div class="trans-btns" id="trans-btns">');
p('        <button class="active" onclick="setTrans(\'CUT\',this)">CUT</button>');
p('        <button onclick="setTrans(\'MIX\',this)">MIX</button>');
p('        <button onclick="setTrans(\'WIPE\',this)">WIPE</button>');
p('        <button onclick="setTrans(\'DIP\',this)">DIP</button>');
p('        <button onclick="setTrans(\'STING\',this)">STING</button>');
p('      </div>');
p('    </div>');
p('    <div>');
p('      <div style="font-size:10px;color:#666;margin-bottom:4px">RATE (frames)</div>');
p('      <input id="rate-input" type="number" min="1" max="250" value="25" style="width:60px;background:#222;color:#eee;border:1px solid #333;padding:4px;border-radius:2px;font-family:monospace">');
p('    </div>');
p('    <button class="btn-cut" onclick="doCut()">CUT</button>');
p('    <button class="btn-auto" onclick="doAuto()">AUTO</button>');
p('    <div>');
p('      <div style="font-size:10px;color:#666;margin-bottom:2px" id="auto-label"></div>');
p('      <div class="progress-bar"><div class="progress-fill" id="auto-progress"></div></div>');
p('    </div>');
p('  </div>');
p('  <div style="margin-top:8px;font-size:10px;color:#555" id="sw-status"></div>');
p('</div>');
p('');
p('<!-- SCOPE VIEW -->');
p('<div id="view-scope" class="view">');
p('  <div class="scope-grid">');
p('    <div class="scope-panel">');
p('      <h3>Waveform Monitor</h3>');
p('      <canvas id="cv-wave" height="180"></canvas>');
p('    </div>');
p('    <div class="scope-panel">');
p('      <h3>Vectorscope</h3>');
p('      <canvas id="cv-vec" height="180"></canvas>');
p('    </div>');
p('    <div class="scope-panel">');
p('      <h3>RGB Parade</h3>');
p('      <canvas id="cv-parade" height="180"></canvas>');
p('    </div>');
p('    <div class="scope-panel">');
p('      <h3>Loudness (LUFS)</h3>');
p('      <canvas id="cv-loud" height="180"></canvas>');
p('    </div>');
p('  </div>');
p('</div>');
p('');
p('<!-- SYNC VIEW -->');
p('<div id="view-sync" class="view">');
p('  <div class="ptp-card">');
p('    <div style="font-size:10px;color:#666;margin-bottom:4px">PTP OFFSET FROM MASTER</div>');
p('    <div class="ptp-offset"><span id="ptp-offset-val">8</span><span> ns</span></div>');
p('    <div class="ptp-meta">');
p('      <div><b id="ptp-locked">LOCKED</b> &nbsp;Status</div>');
p('      <div>Grandmaster: <b id="ptp-gm">NEXUS-GM-01</b></div>');
p('      <div>Domain: <b>0</b></div>');
p('      <div>Clock Class: <b>6</b></div>');
p('      <div>Devices: <b id="ptp-devcount">12</b></div>');
p('    </div>');
p('  </div>');
p('  <div style="font-size:10px;color:#666;margin-bottom:4px">LIVE LOG</div>');
p('  <div class="ptp-log" id="ptp-log"></div>');
p('</div>');
p('');
p('<!-- CONNECT VIEW -->');
p('<div id="view-connect" class="view">');
p('  <div style="font-size:10px;color:#666;margin-bottom:8px">NMOS IS-04 DISCOVERED DEVICES</div>');
p('  <div class="nmos-list" id="nmos-list"></div>');
p('</div>');
p('');
p('<!-- PRE-DEPLOY VIEW -->');
p('<div id="view-predeploy" class="view">');
p('  <div id="phases-container"></div>');
p('  <div class="go-banner nogo" id="go-banner">⛔ NO-GO — Complete all checks before deployment</div>');
p('</div>');
p('');
p('<!-- STATUS BAR -->');
p('<div class="statusbar" style="padding-bottom:6px">');
p('  <span><span class="dot green" id="sb-ptp-dot"></span>PTP <span id="sb-ptp-txt">LOCKED 8ns</span></span>');
p('  <span class="sep">|</span>');
p('  <span>NMOS <span id="sb-nmos-txt">0 devices</span></span>');
p('  <span class="sep">|</span>');
p('  <span>ST2110 <span id="sb-flows-txt">0 flows</span></span>');
p('  <span class="sep">|</span>');
p('  <span><span class="dot grey" id="sb-ws-dot"></span><span id="sb-ws-txt">WS connecting...</span></span>');
p('  <span class="sep">|</span>');
p('  <span id="sb-clock"></span>');
p('</div>');
p('<div style="height:28px"></div>');

p('<script>');
p('// ── State ──────────────────────────────────────────────────────────────');
p('var pgm = 1, pvw = 2, trans = "CUT";');
p('var mvCols = 4, mvRows = 4;');
p('var ws = null, wsOk = false;');
p('');
p('var SOURCES = [];');
p('for (var i = 1; i <= 32; i++) {');
p('  var n = i <= 24 ? "CAM-" + String(i).padStart(2,"0")');
p('        : i <= 29 ? "REPLAY-0" + (i-24)');
p('        : ["PGM","PVW","GFX"][i-30] || ("SRC-"+i);');
p('  SOURCES.push({id:i, name:n});');
p('}');
p('');
p('// ── Navigation ─────────────────────────────────────────────────────────');
p('function showView(id, btn) {');
p('  document.querySelectorAll(".view").forEach(function(v){v.classList.remove("active")});');
p('  document.querySelectorAll("nav button").forEach(function(b){b.classList.remove("active")});');
p('  document.getElementById("view-"+id).classList.add("active");');
p('  btn.classList.add("active");');
p('  if (id === "scope") startScopes();');
p('}');
p('');
p('// ── MOSAIC ──────────────────────────────────────────────────────────────');
p('function setLayout(r, c, btn) {');
p('  mvRows = r; mvCols = c;');
p('  document.querySelectorAll(".layout-btns button").forEach(function(b){b.classList.remove("active")});');
p('  btn.classList.add("active");');
p('  renderMosaic();');
p('}');
p('');
p('function renderMosaic() {');
p('  var g = document.getElementById("mv-grid");');
p('  g.style.gridTemplateColumns = "repeat("+mvCols+", 1fr)";');
p('  g.innerHTML = "";');
p('  var count = mvRows * mvCols;');
p('  for (var i = 0; i < count; i++) {');
p('    var src = SOURCES[i % SOURCES.length];');
p('    var tally = src.id === pgm ? "pgm" : src.id === pvw ? "pvw" : "";');
p('    var hue = (src.id * 37) % 360;');
p('    var cell = document.createElement("div");');
p('    cell.className = "mv-cell " + tally;');
p('    cell.dataset.srcId = src.id;');
p('    cell.innerHTML =');
p('      "<div class=\\"bg\\" style=\\"background:hsl("+hue+",20%,12%)\\"><span style=\\"color:#333;font-size:9px\\">VIDEO</span></div>" +');
p('      "<div class=\\"lbl\\"><span>"+src.name+"</span>" +');
p('      (tally ? "<span class=\\"tally-tag\\">"+tally.toUpperCase()+"</span>" : "") +');
p('      "</div>";');
p('    cell.onclick = (function(sid){ return function(){ setPvw(sid); }; })(src.id);');
p('    g.appendChild(cell);');
p('  }');
p('}');
p('');
p('// ── SWITCH ──────────────────────────────────────────────────────────────');
p('function renderBuses() {');
p('  var pvwBus = document.getElementById("pvw-bus");');
p('  var pgmBus = document.getElementById("pgm-bus");');
p('  pvwBus.innerHTML = ""; pgmBus.innerHTML = "";');
p('  SOURCES.forEach(function(src) {');
p('    var bp = document.createElement("button");');
p('    bp.textContent = src.name;');
p('    bp.className = src.id === pvw ? "pvw-active" : "";');
p('    bp.onclick = (function(sid){ return function(){ setPvw(sid); }; })(src.id);');
p('    pvwBus.appendChild(bp);');
p('');
p('    var bg = document.createElement("button");');
p('    bg.textContent = src.name;');
p('    bg.className = src.id === pgm ? "pgm-active" : "";');
p('    bg.style.cursor = "default";');
p('    pgmBus.appendChild(bg);');
p('  });');
p('  var s = document.getElementById("sw-status");');
p('  if (s) s.textContent = "PGM: " + (SOURCES[pgm-1]||{name:"?"}).name + "  |  PVW: " + (SOURCES[pvw-1]||{name:"?"}).name;');
p('}');
p('');
p('function setPvw(id) {');
p('  pvw = id;');
p('  renderBuses(); renderMosaic();');
p('  wsSend({type:"SWITCHER_PVW", payload:{source:id}});');
p('}');
p('');
p('function doCut() {');
p('  var tmp = pgm; pgm = pvw; pvw = tmp;');
p('  renderBuses(); renderMosaic();');
p('  wsSend({type:"SWITCHER_CUT", payload:{pvw:pvw, pgm:pgm}});');
p('}');
p('');
p('function doAuto() {');
p('  var rate = parseInt(document.getElementById("rate-input").value) || 25;');
p('  var ms = Math.round((rate / 25) * 1000);');
p('  var fill = document.getElementById("auto-progress");');
p('  var lbl = document.getElementById("auto-label");');
p('  lbl.textContent = trans + " " + rate + "f";');
p('  fill.style.width = "0%";');
p('  var start = Date.now();');
p('  var timer = setInterval(function() {');
p('    var pct = Math.min(100, ((Date.now()-start)/ms)*100);');
p('    fill.style.width = pct + "%";');
p('    if (pct >= 100) {');
p('      clearInterval(timer);');
p('      lbl.textContent = "";');
p('      var tmp2 = pgm; pgm = pvw; pvw = tmp2;');
p('      renderBuses(); renderMosaic();');
p('      wsSend({type:"SWITCHER_AUTO", payload:{transition:trans, rate:rate}});');
p('    }');
p('  }, 40);');
p('}');
p('');
p('function setTrans(t, btn) {');
p('  trans = t;');
p('  document.querySelectorAll("#trans-btns button").forEach(function(b){b.classList.remove("active")});');
p('  btn.classList.add("active");');
p('}');
p('');
p('// ── SCOPE ───────────────────────────────────────────────────────────────');
p('var scopeTimer = null;');
p('function startScopes() {');
p('  if (scopeTimer) return;');
p('  drawScopes();');
p('  scopeTimer = setInterval(drawScopes, 80);');
p('}');
p('');
p('function drawScopes() {');
p('  drawWaveform();');
p('  drawVectorscope();');
p('  drawParade();');
p('  drawLoudness();');
p('}');
p('');
p('function resizeCanvas(id) {');
p('  var c = document.getElementById(id);');
p('  var w = c.parentElement.clientWidth - 16;');
p('  if (c.width !== w) { c.width = w; }');
p('  return c;');
p('}');
p('');
p('function drawWaveform() {');
p('  var c = resizeCanvas("cv-wave");');
p('  var ctx = c.getContext("2d");');
p('  var W = c.width, H = c.height;');
p('  ctx.fillStyle = "#000"; ctx.fillRect(0,0,W,H);');
p('  // grid lines');
p('  ctx.strokeStyle = "#1a1a1a"; ctx.lineWidth = 1;');
p('  for (var y = 0; y <= 4; y++) {');
p('    ctx.beginPath(); ctx.moveTo(0, H*y/4); ctx.lineTo(W, H*y/4); ctx.stroke();');
p('  }');
p('  // waveform');
p('  ctx.strokeStyle = "#0f0"; ctx.lineWidth = 1.5;');
p('  ctx.beginPath();');
p('  var t = Date.now()/1000;');
p('  for (var x = 0; x < W; x++) {');
p('    var v = 0.5 + 0.35*Math.sin(x/W*Math.PI*2 + t) + 0.05*Math.sin(x/W*Math.PI*8 + t*2);');
p('    var py = H - v*H;');
p('    x === 0 ? ctx.moveTo(x,py) : ctx.lineTo(x,py);');
p('  }');
p('  ctx.stroke();');
p('  ctx.fillStyle="#0f0"; ctx.font="9px monospace";');
p('  ctx.fillText("100%",2,10); ctx.fillText("0%",2,H-2);');
p('}');
p('');
p('function drawVectorscope() {');
p('  var c = resizeCanvas("cv-vec");');
p('  var ctx = c.getContext("2d");');
p('  var W = c.width, H = c.height;');
p('  var cx = W/2, cy = H/2, r = Math.min(W,H)*0.45;');
p('  ctx.fillStyle = "#000"; ctx.fillRect(0,0,W,H);');
p('  // graticule');
p('  ctx.strokeStyle = "#1a1a1a"; ctx.lineWidth = 1;');
p('  ctx.beginPath(); ctx.arc(cx,cy,r,0,Math.PI*2); ctx.stroke();');
p('  ctx.beginPath(); ctx.moveTo(cx-r,cy); ctx.lineTo(cx+r,cy); ctx.stroke();');
p('  ctx.beginPath(); ctx.moveTo(cx,cy-r); ctx.lineTo(cx,cy+r); ctx.stroke();');
p('  // color targets');
p('  var targets=[{a:0,c:"#f00"},{a:60,c:"#ff0"},{a:120,c:"#0f0"},{a:180,c:"#0ff"},{a:240,c:"#00f"},{a:300,c:"#f0f"}];');
p('  targets.forEach(function(t){');
p('    var rad=t.a*Math.PI/180;');
p('    var tx=cx+r*0.75*Math.cos(rad), ty=cy-r*0.75*Math.sin(rad);');
p('    ctx.fillStyle=t.c; ctx.beginPath(); ctx.arc(tx,ty,4,0,Math.PI*2); ctx.fill();');
p('  });');
p('  // signal blob');
p('  var now=Date.now()/1000;');
p('  ctx.fillStyle="rgba(0,255,200,0.6)";');
p('  for(var i=0;i<80;i++){');
p('    var angle=(now*0.3+i*0.08)%(Math.PI*2);');
p('    var dist=r*0.4*(0.8+0.2*Math.sin(now+i));');
p('    var px=cx+dist*Math.cos(angle)+((Math.random()-0.5)*6);');
p('    var py=cy+dist*Math.sin(angle)+((Math.random()-0.5)*6);');
p('    ctx.beginPath(); ctx.arc(px,py,1,0,Math.PI*2); ctx.fill();');
p('  }');
p('}');
p('');
p('function drawParade() {');
p('  var c = resizeCanvas("cv-parade");');
p('  var ctx = c.getContext("2d");');
p('  var W = c.width, H = c.height;');
p('  ctx.fillStyle = "#000"; ctx.fillRect(0,0,W,H);');
p('  var t = Date.now()/1000;');
p('  var channels = [{c:"#f44",o:0},{c:"#4f4",o:1},{c:"#44f",o:2}];');
p('  var cw = Math.floor(W/3) - 2;');
p('  channels.forEach(function(ch) {');
p('    var ox = ch.o*(cw+3);');
p('    ctx.strokeStyle = ch.c; ctx.lineWidth = 1.5;');
p('    ctx.beginPath();');
p('    for(var x=0;x<cw;x++){');
p('      var v=0.5+0.3*Math.sin(x/cw*Math.PI*2+t+ch.o)+0.1*Math.sin(x/cw*Math.PI*6+t);');
p('      var py=H-v*H;');
p('      x===0?ctx.moveTo(ox+x,py):ctx.lineTo(ox+x,py);');
p('    }');
p('    ctx.stroke();');
p('  });');
p('  ctx.fillStyle="#555"; ctx.font="9px monospace";');
p('  ctx.fillText("R",4,H-4); ctx.fillText("G",W/3+4,H-4); ctx.fillText("B",2*W/3+4,H-4);');
p('}');
p('');
p('function drawLoudness() {');
p('  var c = resizeCanvas("cv-loud");');
p('  var ctx = c.getContext("2d");');
p('  var W = c.width, H = c.height;');
p('  ctx.fillStyle = "#000"; ctx.fillRect(0,0,W,H);');
p('  var t = Date.now()/1000;');
p('  var channels = ["L","R","C","Ls","Rs","LFE"];');
p('  var bw = Math.floor(W/channels.length) - 3;');
p('  channels.forEach(function(ch,i){');
p('    var level = 0.55 + 0.3*Math.sin(t*1.3+i*1.1) + 0.1*Math.random();');
p('    level = Math.max(0.05, Math.min(0.98, level));');
p('    var bh = level*H;');
p('    var color = level > 0.9 ? "#f00" : level > 0.75 ? "#fa0" : "#0af";');
p('    var ox = i*(bw+3);');
p('    ctx.fillStyle = "#111"; ctx.fillRect(ox,0,bw,H);');
p('    ctx.fillStyle = color; ctx.fillRect(ox, H-bh, bw, bh);');
p('    ctx.fillStyle = "#555"; ctx.font = "9px monospace";');
p('    ctx.fillText(ch, ox+2, H-2);');
p('    var lufs = Math.round(-23 + level*20);');
p('    ctx.fillStyle = "#888";');
p('    ctx.fillText(lufs+"L", ox, 10);');
p('  });');
p('}');

p('');
p('// ── SYNC / PTP ──────────────────────────────────────────────────────────');
p('function startPtp() {');
p('  updatePtp();');
p('  setInterval(updatePtp, 3000);');
p('}');
p('');
p('function updatePtp() {');
p('  var offset = Math.floor(4 + Math.random()*10);');
p('  document.getElementById("ptp-offset-val").textContent = offset;');
p('  document.getElementById("sb-ptp-txt").textContent = "LOCKED " + offset + "ns";');
p('  var log = document.getElementById("ptp-log");');
p('  var ts = new Date().toLocaleTimeString();');
p('  var entry = document.createElement("div");');
p('  entry.className = "entry";');
p('  entry.innerHTML = "<span class=\\"ts\\">" + ts + "</span>offset=" + offset + "ns  gm=NEXUS-GM-01  domain=0  steps=1";');
p('  log.insertBefore(entry, log.firstChild);');
p('  if (log.children.length > 40) log.removeChild(log.lastChild);');
p('}');
p('');
p('// ── CONNECT / NMOS ──────────────────────────────────────────────────────');
p('var nmos_devices = [');
p('  {id:1, name:"NEXUS-CAM-01", type:"Node", ip:"10.0.1.11", flows:4, connected:true},');
p('  {id:2, name:"NEXUS-CAM-02", type:"Node", ip:"10.0.1.12", flows:4, connected:true},');
p('  {id:3, name:"NEXUS-CAM-03", type:"Node", ip:"10.0.1.13", flows:4, connected:false},');
p('  {id:4, name:"NEXUS-REPLAY-01", type:"Node", ip:"10.0.1.21", flows:8, connected:true},');
p('  {id:5, name:"NEXUS-ROUTER-01", type:"Device", ip:"10.0.1.31", flows:64, connected:true},');
p('  {id:6, name:"NEXUS-MONITOR-01", type:"Receiver", ip:"10.0.1.41", flows:2, connected:false},');
p('  {id:7, name:"NEXUS-ENCODER-01", type:"Sender", ip:"10.0.1.51", flows:4, connected:true},');
p('  {id:8, name:"NEXUS-DECODER-01", type:"Receiver", ip:"10.0.1.52", flows:4, connected:false},');
p('];');
p('');
p('function renderNmos() {');
p('  var list = document.getElementById("nmos-list");');
p('  list.innerHTML = "";');
p('  var connected = 0;');
p('  var totalFlows = 0;');
p('  nmos_devices.forEach(function(dev) {');
p('    if (dev.connected) { connected++; totalFlows += dev.flows; }');
p('    var el = document.createElement("div");');
p('    el.className = "nmos-device";');
p('    el.innerHTML =');
p('      "<div class=\\"info\\">" +');
p('      "<div class=\\"name\\"><span class=\\"dot " + (dev.connected?"on":"off") + "\\"></span>" + dev.name + "</div>" +');
p('      "<div class=\\"meta\\">" + dev.type + " &nbsp;·&nbsp; " + dev.ip + " &nbsp;·&nbsp; " + dev.flows + " flows</div>" +');
p('      "</div>" +');
p('      "<button class=\\"btn-connect " + (dev.connected?"connected":"") + "\\" data-id=\\"" + dev.id + "\\">" +');
p('      (dev.connected ? "DISCONNECT" : "CONNECT") + "</button>";');
p('    list.appendChild(el);');
p('  });');
p('  document.getElementById("sb-nmos-txt").textContent = connected + " devices";');
p('  document.getElementById("sb-flows-txt").textContent = totalFlows + " flows";');
p('  list.querySelectorAll(".btn-connect").forEach(function(btn) {');
p('    btn.onclick = function() {');
p('      var id = parseInt(this.dataset.id);');
p('      var dev = nmos_devices.find(function(d){return d.id===id});');
p('      if (dev) { dev.connected = !dev.connected; renderNmos(); }');
p('    };');
p('  });');
p('}');
p('');
p('// ── PRE-DEPLOY ──────────────────────────────────────────────────────────');
p('var phases = [');
p('  { title: "Phase 1 — Network Infrastructure", items: [');
p('    "10GbE switches configured with VLAN isolation",');
p('    "PTP grandmaster clock installed and locked",');
p('    "Multicast routing enabled on all switches",');
p('    "Network latency < 1ms verified end-to-end"');
p('  ]},');
p('  { title: "Phase 2 — Hardware Integration", items: [');
p('    "FPGA SDI bridge firmware flashed and tested",');
p('    "ST 2110-20 video flows verified on analyzer",');
p('    "ST 2110-30 audio flows verified",');
p('    "PTP sync < 50ns on all endpoints"');
p('  ]},');
p('  { title: "Phase 3 — Software Services", items: [');
p('    "Kubernetes cluster healthy (all nodes Ready)",');
p('    "NMOS IS-04 registry responding",');
p('    "Switcher service latency < 5ms",');
p('    "Router service routing table loaded"');
p('  ]},');
p('  { title: "Phase 4 — Monitoring & Alerting", items: [');
p('    "Prometheus scraping all targets",');
p('    "Grafana dashboards loading correctly",');
p('    "Alert rules tested and firing correctly",');
p('    "On-call rotation confirmed"');
p('  ]},');
p('  { title: "Phase 5 — Security & Access", items: [');
p('    "JWT secrets rotated for production",');
p('    "Network policies applied in Kubernetes",');
p('    "Operator credentials distributed",');
p('    "Audit logging enabled"');
p('  ]}');
p('];');
p('');
p('var checkState = {};');
p('');
p('function renderPhases() {');
p('  var container = document.getElementById("phases-container");');
p('  container.innerHTML = "";');
p('  phases.forEach(function(phase, pi) {');
p('    var div = document.createElement("div");');
p('    div.className = "phase";');
p('    var h = document.createElement("h3");');
p('    h.textContent = phase.title;');
p('    div.appendChild(h);');
p('    phase.items.forEach(function(item, ii) {');
p('      var key = pi+"-"+ii;');
p('      var row = document.createElement("div");');
p('      row.className = "check-item" + (checkState[key] ? " done" : "");');
p('      var cb = document.createElement("input");');
p('      cb.type = "checkbox";');
p('      cb.checked = !!checkState[key];');
p('      cb.dataset.key = key;');
p('      cb.onchange = function() {');
p('        checkState[this.dataset.key] = this.checked;');
p('        renderPhases(); updateGoBanner();');
p('      };');
p('      var lbl = document.createElement("label");');
p('      lbl.textContent = item;');
p('      row.appendChild(cb); row.appendChild(lbl);');
p('      div.appendChild(row);');
p('    });');
p('    container.appendChild(div);');
p('  });');
p('}');
p('');
p('function updateGoBanner() {');
p('  var total = 0, checked = 0;');
p('  phases.forEach(function(phase,pi){');
p('    phase.items.forEach(function(_,ii){');
p('      total++;');
p('      if (checkState[pi+"-"+ii]) checked++;');
p('    });');
p('  });');
p('  var banner = document.getElementById("go-banner");');
p('  if (checked === total) {');
p('    banner.className = "go-banner go";');
p('    banner.textContent = "✅ GO — All " + total + " checks passed. Ready for deployment.";');
p('  } else {');
p('    banner.className = "go-banner nogo";');
p('    banner.textContent = "⛔ NO-GO — " + checked + "/" + total + " checks complete";');
p('  }');
p('}');
p('');
p('// ── WEBSOCKET ───────────────────────────────────────────────────────────');
p('function initWs() {');
p('  try {');
p('    ws = new WebSocket("ws://localhost:8080/ws/control?token=demo-token");');
p('    ws.onopen = function() {');
p('      wsOk = true;');
p('      document.getElementById("sb-ws-dot").className = "dot green";');
p('      document.getElementById("sb-ws-txt").textContent = "WS connected";');
p('    };');
p('    ws.onclose = function() {');
p('      wsOk = false;');
p('      document.getElementById("sb-ws-dot").className = "dot grey";');
p('      document.getElementById("sb-ws-txt").textContent = "WS offline (demo mode)";');
p('    };');
p('    ws.onerror = function() {');
p('      wsOk = false;');
p('      document.getElementById("sb-ws-dot").className = "dot grey";');
p('      document.getElementById("sb-ws-txt").textContent = "WS offline (demo mode)";');
p('    };');
p('    ws.onmessage = function(e) {');
p('      try {');
p('        var msg = JSON.parse(e.data);');
p('        if (msg.type === "TALLY_UPDATE") {');
p('          pgm = msg.pgm; pvw = msg.pvw;');
p('          renderBuses(); renderMosaic();');
p('        }');
p('      } catch(ex) {}');
p('    };');
p('  } catch(ex) {');
p('    document.getElementById("sb-ws-txt").textContent = "WS offline (demo mode)";');
p('  }');
p('}');
p('');
p('function wsSend(msg) {');
p('  if (ws && wsOk) { try { ws.send(JSON.stringify(msg)); } catch(ex) {} }');
p('}');
p('');
p('// ── CLOCK ───────────────────────────────────────────────────────────────');
p('function updateClock() {');
p('  document.getElementById("sb-clock").textContent = new Date().toLocaleTimeString();');
p('}');
p('');
p('// ── INIT ────────────────────────────────────────────────────────────────');
p('renderMosaic();');
p('renderBuses();');
p('renderNmos();');
p('renderPhases();');
p('updateGoBanner();');
p('startPtp();');
p('initWs();');
p('updateClock();');
p('setInterval(updateClock, 1000);');
p('</script>');
p('</body>');
p('</html>');
p('');
fs.writeFileSync(out, lines.join('\n'), 'utf8');
console.log('Written: ' + out + ' (' + lines.length + ' lines)');
