// NEXUS v6 generator
const fs = require('fs');
const out = [];
const w = s => out.push(s);

w(`<!DOCTYPE html>`);
w(`<html lang="en">`);
w(`<head>`);
w(`<meta charset="UTF-8">`);
w(`<meta name="viewport" content="width=device-width,initial-scale=1">`);
w(`<title>NEXUS v5 — Broadcast Orchestration Platform</title>`);
w(`<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Share+Tech+Mono&display=swap" rel="stylesheet">`);
w(`<style>`);
w(`*{box-sizing:border-box;margin:0;padding:0}`);
w(`:root{`);
w(`  --bg:#020209;--bg2:#05050f;--bg3:#080818;--bg4:#0b0b1e;--bg5:#0f0f28;`);
w(`  --b1:#141430;--b2:#1c1c3a;--b3:#242448;`);
w(`  --acc:#00d4ff;--acc2:#0099bb;--acc3:#005577;`);
w(`  --pgm:#ff1a3a;--pvw:#00ff88;`);
w(`  --warn:#ffaa00;--crit:#ff3355;--ok:#00ff88;`);
w(`  --pur:#bb77ff;--gold:#ffcc33;--teal:#00ffcc;`);
w(`  --t1:#e0e0f0;--t2:#9090b0;--t3:#404060;--t4:#202040;`);
w(`  --font:'Inter',sans-serif;--mono:'Share Tech Mono','Courier New',monospace;`);
w(`  --ease:.12s cubic-bezier(.4,0,.2,1);`);
w(`  --r:4px;--r2:6px;--r3:10px;`);
w(`}`);
w(`html,body{height:100%;overflow:hidden;background:var(--bg)}`);
w(`body{font-family:var(--font);font-size:13px;color:var(--t1);-webkit-font-smoothing:antialiased}`);
w(`button,select,input{font-family:var(--font)}`);
w(`::-webkit-scrollbar{width:4px;height:4px}`);
w(`::-webkit-scrollbar-track{background:transparent}`);
w(`::-webkit-scrollbar-thumb{background:var(--b2);border-radius:2px}`);
w(`body::before{content:'';position:fixed;inset:0;pointer-events:none;z-index:0;`);
w(`  background-image:linear-gradient(rgba(0,212,255,.022) 1px,transparent 1px),linear-gradient(90deg,rgba(0,212,255,.022) 1px,transparent 1px);`);
w(`  background-size:40px 40px}`);
w(``);
w(`/* LOGIN */`);
w(`#login{position:fixed;inset:0;z-index:9999;display:flex;align-items:center;justify-content:center;`);
w(`  background:radial-gradient(ellipse 100% 80% at 50% 0%,rgba(0,212,255,.06) 0%,transparent 60%),var(--bg)}`);
w(`.lg-wrap{width:420px;position:relative;z-index:1}`);
w(`.lg-logo{text-align:center;margin-bottom:44px}`);
w(`.lg-nx{font-size:52px;font-weight:800;letter-spacing:16px;color:var(--acc);`);
w(`  text-shadow:0 0 40px rgba(0,212,255,.5),0 0 80px rgba(0,212,255,.2);`);
w(`  animation:lgpulse 3s ease-in-out infinite}`);
w(`@keyframes lgpulse{0%,100%{text-shadow:0 0 40px rgba(0,212,255,.5),0 0 80px rgba(0,212,255,.2)}`);
w(`  50%{text-shadow:0 0 70px rgba(0,212,255,.8),0 0 140px rgba(0,212,255,.35)}}`);
w(`.lg-sub{font-size:10px;letter-spacing:6px;color:var(--t3);margin-top:10px;font-weight:500}`);
w(`.lg-tagline{font-size:11px;color:var(--t2);margin-top:6px;letter-spacing:1px}`);
w(`.lg-box{background:rgba(8,8,24,.92);border:1px solid var(--b2);border-top:2px solid var(--acc);`);
w(`  padding:32px 36px;border-radius:var(--r3);`);
w(`  box-shadow:0 40px 120px rgba(0,0,0,.9),inset 0 1px 0 rgba(0,212,255,.08);backdrop-filter:blur(20px)}`);
w(`.lg-lbl{font-size:10px;font-weight:600;letter-spacing:2px;color:var(--t3);text-transform:uppercase;margin-bottom:6px;display:block}`);
w(`.lg-inp{width:100%;background:rgba(0,0,0,.4);border:1px solid var(--b2);color:var(--t1);`);
w(`  padding:11px 14px;border-radius:var(--r);margin-bottom:16px;font-size:13px;outline:none;`);
w(`  transition:border-color var(--ease),box-shadow var(--ease)}`);
w(`.lg-inp:focus{border-color:var(--acc);box-shadow:0 0 0 3px rgba(0,212,255,.1)}`);
w(`.lg-sel{width:100%;background:rgba(0,0,0,.4);border:1px solid var(--b2);color:var(--t1);`);
w(`  padding:10px 12px;border-radius:var(--r);margin-bottom:22px;font-size:12px;outline:none;cursor:pointer}`);
w(`.lg-btn{width:100%;background:linear-gradient(135deg,var(--acc),var(--acc2));color:#000;`);
w(`  border:none;padding:14px;font-size:11px;font-weight:700;letter-spacing:4px;`);
w(`  border-radius:var(--r);cursor:pointer;text-transform:uppercase;transition:all var(--ease)}`);
w(`.lg-btn:hover{filter:brightness(1.15);box-shadow:0 0 40px rgba(0,212,255,.5)}`);
w(`.lg-err{color:var(--pgm);font-size:10px;letter-spacing:1px;margin-bottom:12px;display:none;font-weight:600}`);
w(`.lg-hint{color:var(--t3);font-size:10px;text-align:center;margin-top:14px;letter-spacing:1px}`);
w(`.lg-roles{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-bottom:20px}`);
w(`.lg-role-card{padding:10px 12px;border:1px solid var(--b2);border-radius:var(--r);cursor:pointer;`);
w(`  transition:all var(--ease);background:rgba(0,0,0,.3)}`);
w(`.lg-role-card:hover{border-color:var(--acc);background:rgba(0,212,255,.05)}`);
w(`.lg-role-card.sel{border-color:var(--acc);background:rgba(0,212,255,.1);box-shadow:0 0 0 1px var(--acc)}`);
w(`.lg-role-card .rc-name{font-size:11px;font-weight:700;letter-spacing:1px;color:var(--t1)}`);
w(`.lg-role-card .rc-desc{font-size:9px;color:var(--t3);margin-top:3px}`);

w(``);
w(`/* APP SHELL */`);
w(`#app{display:none;flex-direction:column;height:100vh;position:relative;z-index:1}`);
w(``);
w(`/* TOPBAR */`);
w(`#topbar{height:48px;display:flex;align-items:stretch;background:rgba(5,5,15,.95);`);
w(`  border-bottom:1px solid var(--b1);flex-shrink:0;position:relative;z-index:300;backdrop-filter:blur(20px)}`);
w(`#topbar::after{content:'';position:absolute;bottom:0;left:0;right:0;height:1px;`);
w(`  background:linear-gradient(90deg,transparent,rgba(0,212,255,.5) 30%,rgba(0,212,255,.5) 70%,transparent);opacity:.4}`);
w(`.tb-brand{padding:0 20px;display:flex;align-items:center;gap:12px;border-right:1px solid var(--b1);flex-shrink:0}`);
w(`.tb-nx{font-size:18px;font-weight:800;letter-spacing:6px;color:var(--acc)}`);
w(`.tb-v{font-size:8px;color:var(--t3);letter-spacing:3px;margin-top:2px;font-weight:500}`);
w(`.tb-nav{display:flex;flex:1;overflow-x:auto;overflow-y:visible}`);
w(`.tb-nav::-webkit-scrollbar{height:0}`);
w(``);
w(`/* DROPDOWN NAV */`);
w(`.nav-group{position:relative;display:flex;align-items:stretch}`);
w(`.nav-group-btn{height:100%;padding:0 16px;font-size:10px;font-weight:600;letter-spacing:2px;`);
w(`  border:none;background:transparent;color:var(--t3);cursor:pointer;`);
w(`  border-bottom:2px solid transparent;transition:all var(--ease);`);
w(`  white-space:nowrap;text-transform:uppercase;display:flex;align-items:center;gap:6px}`);
w(`.nav-group-btn:hover{color:var(--t1);background:rgba(255,255,255,.03)}`);
w(`.nav-group-btn.open,.nav-group-btn.has-active{color:var(--acc);border-bottom-color:var(--acc)}`);
w(`.nav-group-btn .arrow{font-size:8px;transition:transform var(--ease)}`);
w(`.nav-group-btn.open .arrow{transform:rotate(180deg)}`);
w(`.nav-dropdown{position:absolute;top:100%;left:0;min-width:200px;`);
w(`  background:rgba(8,8,24,.98);border:1px solid var(--b2);border-top:2px solid var(--acc);`);
w(`  border-radius:0 0 var(--r2) var(--r2);box-shadow:0 20px 60px rgba(0,0,0,.8);`);
w(`  display:none;z-index:500;backdrop-filter:blur(20px)}`);
w(`.nav-group:hover .nav-dropdown,.nav-group.open .nav-dropdown{display:block}`);
w(`.nav-dd-item{display:flex;align-items:center;gap:10px;padding:10px 16px;cursor:pointer;`);
w(`  transition:background var(--ease);border-bottom:1px solid rgba(255,255,255,.03)}`);
w(`.nav-dd-item:hover{background:rgba(0,212,255,.07)}`);
w(`.nav-dd-item.active{background:rgba(0,212,255,.1);color:var(--acc)}`);
w(`.nav-dd-item.locked{opacity:.35;cursor:not-allowed}`);
w(`.nav-dd-icon{font-size:14px;width:20px;text-align:center;flex-shrink:0}`);
w(`.nav-dd-label{font-size:11px;font-weight:600;letter-spacing:.5px}`);
w(`.nav-dd-desc{font-size:9px;color:var(--t3);margin-top:1px}`);
w(`.nav-dd-badge{margin-left:auto;font-size:8px;font-weight:700;padding:1px 5px;`);
w(`  border-radius:8px;background:var(--pgm);color:#fff}`);
w(`.nav-dd-sep{height:1px;background:var(--b1);margin:4px 0}`);
w(`.nav-dd-grp-lbl{font-size:8px;font-weight:700;letter-spacing:2px;color:var(--t3);`);
w(`  padding:8px 16px 4px;text-transform:uppercase}`);
w(``);
w(`/* DIRECT NAV BUTTONS (single items) */`);
w(`.nb{height:100%;padding:0 14px;font-size:10px;font-weight:600;letter-spacing:1.5px;`);
w(`  border:none;background:transparent;color:var(--t3);cursor:pointer;`);
w(`  border-bottom:2px solid transparent;transition:all var(--ease);`);
w(`  white-space:nowrap;text-transform:uppercase;position:relative}`);
w(`.nb:hover{color:var(--t1);background:rgba(255,255,255,.03)}`);
w(`.nb.on{color:var(--acc);border-bottom-color:var(--acc);background:rgba(0,212,255,.04)}`);
w(``);
w(`/* STATUS BAR */`);
w(`#sbar{height:28px;display:flex;align-items:stretch;background:rgba(3,3,12,.9);`);
w(`  border-bottom:1px solid var(--b1);flex-shrink:0;font-size:10px;overflow:hidden}`);
w(`.si{display:flex;align-items:center;gap:6px;padding:0 12px;`);
w(`  border-right:1px solid var(--b1);flex-shrink:0;white-space:nowrap}`);
w(`.si-lbl{font-size:8px;font-weight:600;letter-spacing:2px;color:var(--t3);text-transform:uppercase}`);
w(`.si-tc{font-family:var(--mono);font-size:11px;color:var(--ok);letter-spacing:2px}`);
w(`.si-pgm{color:var(--pgm);font-weight:700;font-size:11px}`);
w(`.si-pvw{color:var(--pvw);font-weight:700;font-size:11px}`);
w(`.si-ptp{color:var(--acc);font-size:9px;font-family:var(--mono)}`);
w(`.si-sp{flex:1}`);
w(`.si-air{color:var(--pgm);font-size:9px;font-weight:700;letter-spacing:3px}`);
w(`.si-role{padding:0 12px;font-size:9px;font-weight:700;letter-spacing:2px;`);
w(`  text-transform:uppercase;display:flex;align-items:center;gap:6px}`);
w(`.si-env{padding:0 10px;font-size:8px;font-weight:600;letter-spacing:1px;`);
w(`  display:flex;align-items:center;gap:5px;border-right:1px solid var(--b1)}`);
w(``);
w(`/* MAIN */`);
w(`#main{flex:1;overflow:hidden;position:relative}`);
w(`.view{display:none;width:100%;height:100%;overflow:auto;flex-direction:column}`);
w(`.view.on{display:flex}`);
w(``);
w(`/* PANELS */`);
w(`.pnl{background:var(--bg3);border:1px solid var(--b1);border-radius:var(--r2);overflow:hidden}`);
w(`.pnl-h{display:flex;align-items:center;justify-content:space-between;padding:8px 14px;`);
w(`  background:var(--bg4);border-bottom:1px solid var(--b1);flex-shrink:0;gap:8px}`);
w(`.pnl-t{font-size:9px;font-weight:700;letter-spacing:2.5px;color:var(--acc);text-transform:uppercase}`);
w(`.pnl-sub{font-size:9px;color:var(--t3)}`);
w(``);
w(`/* TABS */`);
w(`.tbar{display:flex;background:var(--bg4);border-bottom:1px solid var(--b1);flex-shrink:0;overflow-x:auto}`);
w(`.tab{padding:9px 18px;font-size:9px;font-weight:700;letter-spacing:2px;color:var(--t3);`);
w(`  cursor:pointer;border-bottom:2px solid transparent;transition:all var(--ease);`);
w(`  text-transform:uppercase;white-space:nowrap;user-select:none;flex-shrink:0}`);
w(`.tab:hover{color:var(--t1);background:rgba(255,255,255,.02)}`);
w(`.tab.on{color:var(--acc);border-bottom-color:var(--acc);background:rgba(0,212,255,.04)}`);
w(`.tp{display:none;flex:1;overflow:auto}.tp.on{display:block}`);
w(``);
w(`/* BUTTONS */`);
w(`.btn{padding:5px 12px;font-size:10px;font-weight:600;letter-spacing:.5px;border-radius:var(--r);`);
w(`  border:1px solid var(--b2);background:var(--bg4);color:var(--t2);`);
w(`  cursor:pointer;transition:all var(--ease);text-transform:uppercase;white-space:nowrap;user-select:none}`);
w(`.btn:hover{border-color:var(--acc);color:var(--acc);background:rgba(0,212,255,.06)}`);
w(`.btn:active{transform:scale(.97)}`);
w(`.btn-pgm{border-color:var(--pgm)!important;background:rgba(255,26,58,.12)!important;color:var(--pgm)!important}`);
w(`.btn-pvw{border-color:var(--pvw)!important;background:rgba(0,255,136,.08)!important;color:var(--pvw)!important}`);
w(`.btn-acc{border-color:var(--acc)!important;background:rgba(0,212,255,.1)!important;color:var(--acc)!important}`);
w(`.btn-warn{border-color:var(--warn)!important;background:rgba(255,170,0,.08)!important;color:var(--warn)!important}`);
w(`.btn-pur{border-color:var(--pur)!important;background:rgba(187,119,255,.08)!important;color:var(--pur)!important}`);
w(`.btn-gold{border-color:var(--gold)!important;background:rgba(255,204,51,.08)!important;color:var(--gold)!important}`);
w(`.btn-teal{border-color:var(--teal)!important;background:rgba(0,255,204,.08)!important;color:var(--teal)!important}`);
w(`.btn-lg{padding:9px 22px!important;font-size:11px!important;letter-spacing:2px!important}`);
w(`.btn-xl{padding:13px 30px!important;font-size:13px!important;letter-spacing:3px!important}`);
w(`.btn-sm{padding:3px 8px!important;font-size:9px!important}`);
w(`.btn-icon{padding:5px 8px!important;font-size:13px!important;line-height:1}`);
w(`.btn:disabled,.btn-locked{opacity:.3!important;cursor:not-allowed!important;pointer-events:none!important}`);

w(``);
w(`/* BADGES */`);
w(`.bx{display:inline-flex;align-items:center;padding:2px 7px;border-radius:10px;`);
w(`  font-size:8px;font-weight:700;letter-spacing:1px;text-transform:uppercase}`);
w(`.bx-ok{background:rgba(0,255,136,.1);color:var(--ok);border:1px solid rgba(0,255,136,.25)}`);
w(`.bx-pgm{background:rgba(255,26,58,.15);color:var(--pgm);border:1px solid rgba(255,26,58,.3)}`);
w(`.bx-pvw{background:rgba(0,255,136,.1);color:var(--pvw);border:1px solid rgba(0,255,136,.2)}`);
w(`.bx-warn{background:rgba(255,170,0,.1);color:var(--warn);border:1px solid rgba(255,170,0,.25)}`);
w(`.bx-acc{background:rgba(0,212,255,.08);color:var(--acc);border:1px solid rgba(0,212,255,.2)}`);
w(`.bx-pur{background:rgba(187,119,255,.1);color:var(--pur);border:1px solid rgba(187,119,255,.2)}`);
w(`.bx-gold{background:rgba(255,204,51,.1);color:var(--gold);border:1px solid rgba(255,204,51,.2)}`);
w(`.bx-teal{background:rgba(0,255,204,.08);color:var(--teal);border:1px solid rgba(0,255,204,.2)}`);
w(``);
w(`/* DOTS */`);
w(`.dot{width:7px;height:7px;border-radius:50%;display:inline-block;flex-shrink:0}`);
w(`.dot-ok{background:var(--ok);box-shadow:0 0 8px var(--ok)}`);
w(`.dot-pgm{background:var(--pgm);box-shadow:0 0 8px var(--pgm)}`);
w(`.dot-pvw{background:var(--pvw);box-shadow:0 0 7px var(--pvw)}`);
w(`.dot-warn{background:var(--warn);box-shadow:0 0 7px var(--warn)}`);
w(`.dot-off{background:var(--t3)}`);
w(`.dot-acc{background:var(--acc);box-shadow:0 0 7px var(--acc)}`);
w(`.dot-pur{background:var(--pur);box-shadow:0 0 7px var(--pur)}`);
w(`.dot-pulse{animation:dp 1.2s ease-in-out infinite}`);
w(`@keyframes dp{0%,100%{opacity:1}50%{opacity:.2}}`);
w(``);
w(`/* MISC */`);
w(`.lbl{font-size:9px;font-weight:600;letter-spacing:2px;color:var(--t3);text-transform:uppercase}`);
w(`.mono{font-family:var(--mono)}`);
w(`.sep-v{width:1px;background:var(--b1);align-self:stretch;flex-shrink:0}`);
w(`.sep-h{height:1px;background:var(--b1);width:100%;margin:6px 0}`);
w(`.tag{display:inline-block;padding:2px 6px;border-radius:3px;font-size:8px;font-weight:700;`);
w(`  letter-spacing:1px;text-transform:uppercase;background:var(--bg4);color:var(--t3);border:1px solid var(--b1)}`);
w(`.inp{background:var(--bg2);border:1px solid var(--b2);color:var(--t1);`);
w(`  padding:6px 10px;border-radius:var(--r);font-size:11px;outline:none;transition:border-color var(--ease)}`);
w(`.inp:focus{border-color:var(--acc)}`);
w(`.sel{background:var(--bg2);border:1px solid var(--b2);color:var(--t1);`);
w(`  padding:5px 8px;border-radius:var(--r);font-size:10px;outline:none;cursor:pointer}`);
w(`@keyframes fadeUp{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}`);
w(`.anim{animation:fadeUp .18s ease-out}`);
w(`@keyframes slideIn{from{opacity:0;transform:translateX(-8px)}to{opacity:1;transform:translateX(0)}}`);
w(``);
w(`/* SCANLINE */`);
w(`.scanline{position:fixed;top:0;left:0;right:0;height:2px;pointer-events:none;z-index:9997;`);
w(`  background:linear-gradient(transparent,rgba(0,212,255,.04),transparent);`);
w(`  animation:scan 14s linear infinite}`);
w(`@keyframes scan{from{top:-2px}to{top:100vh}}`);
w(``);
w(`/* MOSAIC */`);
w(`.mv-grid{display:grid;gap:3px;padding:6px;flex:1;min-height:0}`);
w(`.mv-tile{position:relative;background:#000;border-radius:var(--r);overflow:hidden;`);
w(`  cursor:pointer;border:2px solid transparent;transition:border-color .1s;aspect-ratio:16/9}`);
w(`.mv-tile:hover{border-color:rgba(0,212,255,.4)}`);
w(`.mv-tile.t-pgm{border-color:var(--pgm)!important;box-shadow:0 0 0 1px var(--pgm),inset 0 0 30px rgba(255,26,58,.1)}`);
w(`.mv-tile.t-pvw{border-color:var(--pvw)!important;box-shadow:0 0 0 1px var(--pvw),inset 0 0 20px rgba(0,255,136,.07)}`);
w(`.mv-tile.t-sel{border-color:var(--acc)!important;box-shadow:0 0 0 1px var(--acc)}`);
w(`.tile-cv{width:100%;height:100%;display:block}`);
w(`.tile-ov{position:absolute;inset:0;display:flex;flex-direction:column;`);
w(`  justify-content:space-between;padding:5px;pointer-events:none}`);
w(`.tile-lbl{font-size:9px;font-weight:700;padding:2px 6px;background:rgba(0,0,0,.75);`);
w(`  border-radius:3px;display:inline-block;backdrop-filter:blur(4px)}`);
w(`.tile-bot{display:flex;align-items:center;justify-content:space-between}`);
w(`.tile-tc{font-family:var(--mono);font-size:7px;color:rgba(255,255,255,.4);`);
w(`  background:rgba(0,0,0,.5);padding:1px 4px;border-radius:2px}`);
w(`.tile-bx{font-size:7px;font-weight:700;padding:1px 5px;border-radius:2px;letter-spacing:1px}`);
w(`.tile-bx.pgm{background:var(--pgm);color:#fff}`);
w(`.tile-bx.pvw{background:var(--pvw);color:#000}`);
w(`.tile-menu{position:absolute;inset:0;background:rgba(2,2,9,.95);`);
w(`  display:none;flex-direction:column;z-index:20;backdrop-filter:blur(16px)}`);
w(`.mv-tile.menu-on .tile-menu{display:flex}`);
w(`.tm-hdr{padding:7px 10px;border-bottom:1px solid var(--b1);font-size:9px;font-weight:700;`);
w(`  letter-spacing:2px;color:var(--acc);display:flex;justify-content:space-between;align-items:center;flex-shrink:0}`);
w(`.tm-list{flex:1;overflow-y:auto;padding:4px}`);
w(`.tm-grp{font-size:8px;letter-spacing:2px;color:var(--t3);padding:6px 8px 3px;text-transform:uppercase;font-weight:600}`);
w(`.tm-item{padding:6px 9px;border-radius:var(--r);cursor:pointer;font-size:10px;font-weight:600;`);
w(`  display:flex;align-items:center;gap:8px;transition:background .08s;pointer-events:all}`);
w(`.tm-item:hover{background:rgba(0,212,255,.09)}`);
w(`.tm-item.cur{background:rgba(0,212,255,.14);color:var(--acc)}`);
w(``);
w(`/* SWITCHER */`);
w(`.me-bank{background:var(--bg3);border:1px solid var(--b1);border-radius:var(--r2);overflow:hidden;margin-bottom:8px}`);
w(`.me-hdr{display:flex;align-items:center;gap:10px;padding:8px 14px;background:var(--bg4);border-bottom:1px solid var(--b1)}`);
w(`.me-name{font-size:12px;font-weight:800;letter-spacing:3px}`);
w(`.me-row{padding:8px 12px;border-bottom:1px solid var(--b1)}`);
w(`.me-rlbl{font-size:8px;letter-spacing:2px;font-weight:700;margin-bottom:5px;text-transform:uppercase}`);
w(`.src-grid{display:flex;flex-wrap:wrap;gap:3px}`);
w(`.sb{padding:4px 8px;font-size:9px;font-weight:600;border-radius:3px;`);
w(`  border:1px solid var(--b2);background:var(--bg2);color:var(--t3);`);
w(`  cursor:pointer;transition:all .08s;white-space:nowrap}`);
w(`.sb:hover{border-color:var(--acc);color:var(--acc)}`);
w(`.sb.pvw{background:rgba(0,255,136,.12);border-color:var(--pvw);color:var(--pvw);font-weight:700}`);
w(`.sb.pgm{background:rgba(255,26,58,.12);border-color:var(--pgm);color:var(--pgm);font-weight:700;cursor:default}`);
w(`.me-trans{padding:8px 12px;display:flex;align-items:center;gap:8px;flex-wrap:wrap;background:rgba(0,0,0,.2)}`);
w(`.trans-track{flex:1;height:5px;background:var(--b1);border-radius:3px;overflow:hidden;min-width:80px}`);
w(`.trans-fill{height:100%;border-radius:3px;width:0%;transition:width .04s linear}`);
w(``);
w(`/* KEYER */`);
w(`.key-row{display:flex;align-items:center;gap:8px;padding:6px 12px;border-bottom:1px solid var(--b1)}`);
w(`.key-num{font-size:9px;font-weight:700;color:var(--t3);width:20px;flex-shrink:0}`);
w(`.key-type{font-size:9px;font-weight:600;width:50px;flex-shrink:0}`);
w(`.key-on{width:36px;height:20px;border-radius:10px;border:1px solid var(--b2);background:var(--bg2);`);
w(`  cursor:pointer;position:relative;transition:all .15s;flex-shrink:0}`);
w(`.key-on.active{background:var(--acc);border-color:var(--acc);box-shadow:0 0 10px rgba(0,212,255,.4)}`);
w(`.key-on::after{content:'';position:absolute;top:2px;left:2px;width:14px;height:14px;`);
w(`  border-radius:50%;background:#fff;transition:left .15s}`);
w(`.key-on.active::after{left:18px}`);
w(``);
w(`/* ROUTER */`);
w(`.rt-table{border-collapse:collapse;font-size:9px;white-space:nowrap}`);
w(`.rt-table th{background:var(--bg4);color:var(--t2);padding:5px 9px;`);
w(`  border:1px solid var(--b1);font-weight:700;position:sticky;top:0;z-index:2;font-size:8px;letter-spacing:1px}`);
w(`.rt-table th:first-child{left:0;z-index:3}`);
w(`.rt-table td{border:1px solid var(--b1);padding:4px 7px;background:var(--bg2);`);
w(`  text-align:center;cursor:pointer;transition:background .08s;min-width:54px}`);
w(`.rt-table td:first-child{background:var(--bg4);color:var(--t2);font-weight:600;`);
w(`  text-align:left;position:sticky;left:0;cursor:default;min-width:80px}`);
w(`.rt-table td.xpt{background:rgba(0,212,255,.18);color:var(--acc);font-weight:700}`);
w(`.rt-table td:not(:first-child):hover{background:rgba(0,212,255,.08)}`);
w(``);
w(`/* SIGNAL FLOW */`);
w(`#flow-canvas{position:absolute;inset:0;pointer-events:none;z-index:1}`);
w(`.flow-wrap{position:relative;flex:1;overflow:hidden}`);
w(`.flow-node{position:absolute;background:var(--bg3);border:1px solid var(--b2);border-radius:var(--r2);`);
w(`  padding:10px 14px;cursor:grab;user-select:none;min-width:130px;z-index:2;`);
w(`  box-shadow:0 4px 20px rgba(0,0,0,.5);transition:border-color .15s}`);
w(`.flow-node:hover{border-color:var(--acc)}`);
w(`.flow-node.dragging{cursor:grabbing;box-shadow:0 8px 40px rgba(0,0,0,.8);z-index:10}`);
w(`.flow-node.selected{border-color:var(--acc);box-shadow:0 0 0 2px rgba(0,212,255,.3)}`);
w(`.fn-type{font-size:7px;font-weight:700;letter-spacing:2px;color:var(--t3);text-transform:uppercase;margin-bottom:4px}`);
w(`.fn-name{font-size:11px;font-weight:700;color:var(--t1)}`);
w(`.fn-status{font-size:8px;color:var(--t2);margin-top:3px;display:flex;align-items:center;gap:5px}`);
w(`.fn-ports{display:flex;justify-content:space-between;margin-top:8px;gap:4px}`);
w(`.fn-port{width:10px;height:10px;border-radius:50%;border:2px solid var(--b2);background:var(--bg2);`);
w(`  cursor:crosshair;transition:all .1s;flex-shrink:0}`);
w(`.fn-port:hover,.fn-port.active{border-color:var(--acc);background:var(--acc);box-shadow:0 0 8px var(--acc)}`);
w(`.fn-port.connected{border-color:var(--pvw);background:var(--pvw)}`);
w(`.fn-port.pgm{border-color:var(--pgm);background:var(--pgm)}`);
w(``);
w(`/* RACK */`);
w(`.ru{display:flex;align-items:center;gap:8px;padding:6px 10px;border-radius:var(--r);`);
w(`  border:1px solid var(--b1);background:var(--bg2);margin-bottom:3px;`);
w(`  border-left:3px solid transparent;transition:border-left-color .15s}`);
w(`.ru:hover{border-left-color:var(--acc)}`);
w(``);
w(`/* ALARM */`);
w(`.al-row{display:flex;align-items:center;gap:8px;padding:6px 10px;border-radius:var(--r);`);
w(`  border-left:3px solid transparent;margin-bottom:2px;font-size:10px}`);
w(``);
w(`/* TALLY */`);
w(`.tally-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(110px,1fr));gap:5px}`);
w(`.tc{border-radius:var(--r2);padding:9px;text-align:center;border:1px solid var(--b1);`);
w(`  cursor:pointer;transition:all .1s;background:var(--bg2)}`);
w(`.tc.pgm{background:rgba(255,26,58,.18);border-color:var(--pgm);box-shadow:0 0 16px rgba(255,26,58,.2)}`);
w(`.tc.pvw{background:rgba(0,255,136,.1);border-color:var(--pvw)}`);
w(`.tc.off{opacity:.4}`);
w(``);
w(`/* KV TABLE */`);
w(`.kv{width:100%}`);
w(`.kv tr{border-bottom:1px solid var(--b1)}`);
w(`.kv td{padding:6px 0;font-size:10px}`);
w(`.kv td:first-child{color:var(--t3);font-size:9px;font-weight:600;letter-spacing:1px;text-transform:uppercase;width:45%}`);
w(`.kv td:last-child{color:var(--t1);font-weight:600;text-align:right}`);
w(``);
w(`/* TRAINING */`);
w(`.tr-module{border:1px solid var(--b1);border-radius:var(--r2);overflow:hidden;margin-bottom:6px;`);
w(`  transition:border-color .15s;cursor:pointer}`);
w(`.tr-module:hover{border-color:var(--acc)}`);
w(`.tr-module.active{border-color:var(--acc);box-shadow:0 0 0 1px rgba(0,212,255,.2)}`);
w(`.tr-module.done{border-color:var(--ok)}`);
w(`.tr-mod-hdr{display:flex;align-items:center;gap:10px;padding:12px 14px;background:var(--bg4)}`);
w(`.tr-mod-icon{font-size:20px;width:32px;text-align:center;flex-shrink:0}`);
w(`.tr-mod-title{font-size:12px;font-weight:700;color:var(--t1)}`);
w(`.tr-mod-meta{font-size:9px;color:var(--t3);margin-top:2px}`);
w(`.tr-step-card{background:var(--bg3);border:1px solid var(--b1);border-top:2px solid var(--acc);`);
w(`  border-radius:var(--r2);padding:24px;margin-bottom:16px}`);
w(`.tr-step-num{font-size:9px;font-weight:700;letter-spacing:2px;color:var(--t3);text-transform:uppercase;margin-bottom:8px}`);
w(`.tr-step-title{font-size:20px;font-weight:700;color:var(--t1);margin-bottom:14px;line-height:1.3}`);
w(`.tr-step-body{font-size:13px;color:var(--t2);line-height:1.8}`);
w(`.tr-step-body strong{color:var(--acc);font-weight:600}`);
w(`.tr-step-body code{font-family:var(--mono);background:var(--bg4);padding:1px 5px;border-radius:3px;font-size:11px;color:var(--pvw)}`);
w(`.tr-quiz{background:rgba(0,212,255,.04);border:1px solid rgba(0,212,255,.15);border-radius:var(--r2);padding:16px;margin-top:16px}`);
w(`.tr-quiz-q{font-size:12px;font-weight:600;color:var(--t1);margin-bottom:12px}`);
w(`.tr-quiz-opt{display:flex;align-items:center;gap:10px;padding:9px 12px;border-radius:var(--r);`);
w(`  border:1px solid var(--b2);margin-bottom:6px;cursor:pointer;transition:all .1s;font-size:11px}`);
w(`.tr-quiz-opt:hover{border-color:var(--acc);background:rgba(0,212,255,.05)}`);
w(`.tr-quiz-opt.correct{border-color:var(--ok);background:rgba(0,255,136,.08);color:var(--ok)}`);
w(`.tr-quiz-opt.wrong{border-color:var(--pgm);background:rgba(255,26,58,.08);color:var(--pgm)}`);
w(`.tr-progress{height:3px;background:var(--b1);border-radius:2px;overflow:hidden;margin-top:8px}`);
w(`.tr-progress-fill{height:100%;background:linear-gradient(90deg,var(--acc),var(--pvw));border-radius:2px;transition:width .4s ease}`);
w(``);
w(`/* AUTOMATION */`);
w(`.auto-rule{display:flex;align-items:center;gap:8px;padding:10px 12px;border-radius:var(--r);`);
w(`  border:1px solid var(--b1);background:var(--bg2);margin-bottom:4px;transition:border-color .15s}`);
w(`.auto-rule:hover{border-color:var(--acc)}`);
w(`.auto-rule.active{border-left:3px solid var(--ok)}`);
w(`.auto-rule.inactive{border-left:3px solid var(--t3);opacity:.6}`);
w(``);
w(`/* CLOUD */`);
w(`.cloud-region{border:1px solid var(--b2);border-radius:var(--r2);padding:12px;margin-bottom:8px;`);
w(`  background:rgba(0,212,255,.02)}`);
w(`.cloud-region.ground{border-color:var(--gold);background:rgba(255,204,51,.02)}`);
w(`.cloud-region.cloud{border-color:var(--acc);background:rgba(0,212,255,.03)}`);
w(`.cloud-region.hybrid{border-color:var(--pur);background:rgba(187,119,255,.02)}`);
w(`.cloud-region-hdr{font-size:9px;font-weight:700;letter-spacing:2px;text-transform:uppercase;`);
w(`  margin-bottom:10px;display:flex;align-items:center;gap:8px}`);
w(``);
w(`/* TOAST */`);
w(`#toast-wrap{position:fixed;bottom:24px;right:24px;z-index:9999;display:flex;flex-direction:column;gap:8px;pointer-events:none}`);
w(`.toast{padding:12px 16px;border-radius:var(--r2);font-size:11px;`);
w(`  box-shadow:0 8px 32px rgba(0,0,0,.7);animation:fadeUp .15s ease-out;max-width:300px;pointer-events:all}`);
w(`.toast-deny{background:var(--bg3);border:1px solid var(--pgm);border-left:3px solid var(--pgm);color:var(--pgm)}`);
w(`.toast-ok{background:var(--bg3);border:1px solid var(--ok);border-left:3px solid var(--ok);color:var(--ok)}`);
w(`.toast-info{background:var(--bg3);border:1px solid var(--acc);border-left:3px solid var(--acc);color:var(--acc)}`);
w(`.toast-warn{background:var(--bg3);border:1px solid var(--warn);border-left:3px solid var(--warn);color:var(--warn)}`);
w(`.toast-title{font-weight:700;margin-bottom:3px}`);
w(`.toast-body{font-size:9px;color:var(--t2)}`);
w(``);
w(`/* MODAL */`);
w(`.modal-bg{position:fixed;inset:0;z-index:9998;display:flex;align-items:center;justify-content:center;`);
w(`  background:rgba(2,2,9,.85);backdrop-filter:blur(10px)}`);
w(`.modal-box{background:var(--bg3);border:1px solid var(--b2);border-top:2px solid var(--acc);`);
w(`  border-radius:var(--r3);padding:28px 32px;box-shadow:0 40px 100px rgba(0,0,0,.9);min-width:360px;max-width:520px}`);
w(`.modal-title{font-size:16px;font-weight:700;color:var(--acc);margin-bottom:20px}`);
w(``);
w(`/* ROLE COLORS */`);
w(`.role-eng{color:var(--gold)}.role-op{color:var(--acc)}.role-tr{color:var(--pur)}.role-vw{color:var(--t2)}`);
w(`</style>`);
w(`</head>`);
w(`<body>`);
w(`<div class="scanline"></div>`);
w(`<div id="toast-wrap"></div>`);

w(``);
w(`<!-- LOGIN -->`);
w(`<div id="login">`);
w(`  <div class="lg-wrap">`);
w(`    <div class="lg-logo">`);
w(`      <div class="lg-nx">NEXUS</div>`);
w(`      <div class="lg-sub">BROADCAST ORCHESTRATION PLATFORM</div>`);
w(`      <div class="lg-tagline">Ground · Cloud · Hybrid · IP Native</div>`);
w(`    </div>`);
w(`    <div class="lg-box">`);
w(`      <div class="lg-err" id="lg-err">⚠ AUTHENTICATION FAILED — CHECK ACCESS CODE</div>`);
w(`      <label class="lg-lbl">Access Code</label>`);
w(`      <input class="lg-inp" type="password" id="lg-pw" placeholder="••••••••" onkeydown="if(event.key==='Enter')doLogin()">`);
w(`      <label class="lg-lbl" style="margin-bottom:10px">Select Role</label>`);
w(`      <div class="lg-roles" id="lg-roles">`);
w(`        <div class="lg-role-card sel" data-role="ENGINEER" onclick="selRole(this)">`);
w(`          <div class="rc-name">⚙ ENGINEER</div>`);
w(`          <div class="rc-desc">Full system access</div>`);
w(`        </div>`);
w(`        <div class="lg-role-card" data-role="OPERATOR" onclick="selRole(this)">`);
w(`          <div class="rc-name">🎬 OPERATOR</div>`);
w(`          <div class="rc-desc">Production control</div>`);
w(`        </div>`);
w(`        <div class="lg-role-card" data-role="TRAINER" onclick="selRole(this)">`);
w(`          <div class="rc-name">📚 TRAINER</div>`);
w(`          <div class="rc-desc">Training & guided mode</div>`);
w(`        </div>`);
w(`        <div class="lg-role-card" data-role="VIEWER" onclick="selRole(this)">`);
w(`          <div class="rc-name">👁 VIEWER</div>`);
w(`          <div class="rc-desc">Monitor only</div>`);
w(`        </div>`);
w(`      </div>`);
w(`      <button class="lg-btn" onclick="doLogin()">AUTHENTICATE</button>`);
w(`      <div class="lg-hint">Demo access code: nexus2024</div>`);
w(`    </div>`);
w(`  </div>`);
w(`</div>`);
w(``);
w(`<!-- APP -->`);
w(`<div id="app">`);
w(`  <!-- TOPBAR -->`);
w(`  <div id="topbar">`);
w(`    <div class="tb-brand">`);
w(`      <div>`);
w(`        <div class="tb-nx">NEXUS</div>`);
w(`        <div class="tb-v">v5 ORCHESTRATOR</div>`);
w(`      </div>`);
w(`    </div>`);
w(`    <div class="tb-nav" id="tb-nav"></div>`);
w(`    <div style="display:flex;align-items:center;gap:8px;padding:0 14px;border-left:1px solid var(--b1);flex-shrink:0">`);
w(`      <span class="lbl" id="tb-env-lbl" style="color:var(--gold)">HYBRID</span>`);
w(`      <div class="sep-v" style="height:20px"></div>`);
w(`      <span class="lbl" id="tb-role" style="color:var(--acc)">ENGINEER</span>`);
w(`      <span class="dot dot-ok dot-pulse"></span>`);
w(`      <button class="btn btn-sm" onclick="openSwitchUser()" style="margin-left:4px">⇄ SWITCH</button>`);
w(`    </div>`);
w(`  </div>`);
w(`  <!-- STATUS BAR -->`);
w(`  <div id="sbar">`);
w(`    <div class="si"><span class="si-lbl">TC</span><span class="si-tc" id="sb-tc">10:00:00:00</span></div>`);
w(`    <div class="si"><span class="si-lbl">PGM</span><span class="si-pgm" id="sb-pgm">CAM-01</span></div>`);
w(`    <div class="si"><span class="si-lbl">PVW</span><span class="si-pvw" id="sb-pvw">CAM-02</span></div>`);
w(`    <div class="si"><span class="si-ptp" id="sb-ptp">PTP ±1ns</span></div>`);
w(`    <div class="si"><span class="dot dot-off" id="ws-dot"></span><span class="si-lbl" id="ws-lbl">LOCAL</span></div>`);
w(`    <div class="si" id="sb-alm" style="display:none"><span id="sb-alm-txt" style="color:var(--warn);font-size:9px;font-weight:700"></span></div>`);
w(`    <div class="si-sp"></div>`);
w(`    <div class="si si-env"><span class="dot dot-acc"></span><span id="sb-env" style="font-size:9px;font-weight:700;color:var(--acc)">HYBRID</span></div>`);
w(`    <div class="si"><span class="dot dot-pgm dot-pulse"></span>&nbsp;<span class="si-air">ON AIR</span></div>`);
w(`    <div class="si-role" id="sb-role"></div>`);
w(`  </div>`);
w(`  <!-- MAIN -->`);
w(`  <div id="main">`);

// All view containers
const VIEWS_ALL = ['live','mosaic','switcher','router','flow','cloudmcr','srt','scopes','ptp','nmos',
  'devices','api','preflight','rundown','playout','orchestrator','training','compat','network','automation','database'];
VIEWS_ALL.forEach(id => w(`    <div class="view" id="view-${id}"></div>`));

w(`  </div>`);
w(`</div>`);

w(``);
w(`<script>`);
w(`'use strict';`);
w(`// ─── CONSTANTS ───────────────────────────────────────────────────────────────`);
w(`var PW = 'nexus2024';`);
w(`var ROLE = 'VIEWER';`);
w(`var ENV_MODE = 'HYBRID'; // GROUND | CLOUD | HYBRID`);
w(`var _ivs = [];`);
w(`var _tf=0,_ts=0,_tm=0,_th=10;`);
w(`function p2(n){return n<10?'0'+n:''+n;}`);
w(``);
w(`// ─── ROLE DEFINITIONS ────────────────────────────────────────────────────────`);
w(`// ENGINEER: everything`);
w(`// OPERATOR: production only — no engineering, no infra, no API, no DB`);
w(`// TRAINER: training + read-only production views`);
w(`// VIEWER: live/mosaic/scopes/training only`);
w(`var ROLE_CAPS = {`);
w(`  ENGINEER: {canOp:true, canEngineer:true, canAdmin:true, canTrain:true},`);
w(`  OPERATOR: {canOp:true, canEngineer:false, canAdmin:false, canTrain:false},`);
w(`  TRAINER:  {canOp:false, canEngineer:false, canAdmin:false, canTrain:true},`);
w(`  VIEWER:   {canOp:false, canEngineer:false, canAdmin:false, canTrain:false}`);
w(`};`);
w(`function cap(c){return !!(ROLE_CAPS[ROLE]&&ROLE_CAPS[ROLE][c]);}`);
w(`function canOp(){var ok=cap('canOp');if(!ok)toast('deny','ACCESS DENIED','Requires OPERATOR or ENGINEER role');return ok;}`);
w(`function canEngineer(){var ok=cap('canEngineer');if(!ok)toast('deny','ACCESS DENIED','Requires ENGINEER role');return ok;}`);
w(`function canAdmin(){var ok=cap('canAdmin');if(!ok)toast('deny','ACCESS DENIED','Requires ENGINEER role');return ok;}`);
w(``);
w(`// ─── NAV STRUCTURE ───────────────────────────────────────────────────────────`);
w(`// Groups: PRODUCTION, ENGINEERING, SYSTEM, TRAINING`);
w(`var NAV_GROUPS = [`);
w(`  {id:'production', label:'PRODUCTION', icon:'🎬', roles:['ENGINEER','OPERATOR','TRAINER','VIEWER'],`);
w(`   items:[`);
w(`     {id:'live',    label:'Live Monitor',  icon:'📺', desc:'PGM/PVW monitors + system events', roles:['ENGINEER','OPERATOR','TRAINER','VIEWER']},`);
w(`     {id:'mosaic',  label:'Multiviewer',   icon:'⊞',  desc:'Multi-tile mosaic layout',          roles:['ENGINEER','OPERATOR','TRAINER','VIEWER']},`);
w(`     {id:'switcher',label:'Switcher',      icon:'⬡',  desc:'ME banks, keyers, transitions',     roles:['ENGINEER','OPERATOR']},`);
w(`     {id:'rundown', label:'Rundown',       icon:'☰',  desc:'Production cue list & show clock',  roles:['ENGINEER','OPERATOR']},`);
w(`     {id:'playout', label:'Playout',       icon:'▶',  desc:'Channel manager & spin-up/down',    roles:['ENGINEER','OPERATOR']},`);
w(`     {id:'scopes',  label:'Scopes',        icon:'📊', desc:'Waveform, vectorscope, audio',      roles:['ENGINEER','OPERATOR','VIEWER']},`);
w(`   ]},`);
w(`  {id:'routing', label:'ROUTING', icon:'⇄', roles:['ENGINEER','OPERATOR'],`);
w(`   items:[`);
w(`     {id:'router',  label:'IP Router',     icon:'⊕',  desc:'256×256 crosspoint matrix',         roles:['ENGINEER','OPERATOR']},`);
w(`     {id:'flow',    label:'Signal Flow',   icon:'⟶',  desc:'Visual workflow routing canvas',    roles:['ENGINEER','OPERATOR']},`);
w(`     {id:'automation',label:'Automation',  icon:'⚡', desc:'Rule-based auto-routing engine',    roles:['ENGINEER','OPERATOR']},`);
w(`     {id:'nmos',    label:'NMOS Connect',  icon:'⬡',  desc:'IS-04/05/07/08 registry',           roles:['ENGINEER','OPERATOR']},`);
w(`   ]},`);
w(`  {id:'infrastructure', label:'INFRASTRUCTURE', icon:'⚙', roles:['ENGINEER'],`);
w(`   items:[`);
w(`     {id:'cloudmcr',label:'Cloud MCR',     icon:'☁',  desc:'Virtual rack + cloud regions',      roles:['ENGINEER']},`);
w(`     {id:'srt',     label:'SRT/Cloud',     icon:'📡', desc:'SRT streams + AWS Lambda transport',roles:['ENGINEER']},`);
w(`     {id:'ptp',     label:'PTP Sync',      icon:'⏱',  desc:'SMPTE ST 2059-2 clock hierarchy',   roles:['ENGINEER']},`);
w(`     {id:'network', label:'Network',       icon:'🌐', desc:'Interfaces, multicast, unicast',    roles:['ENGINEER']},`);
w(`     {id:'devices', label:'Devices',       icon:'🖥',  desc:'Device compatibility matrix',       roles:['ENGINEER']},`);
w(`     {id:'database',label:'Database',      icon:'🗄',  desc:'State persistence & config store',  roles:['ENGINEER']},`);
w(`   ]},`);
w(`  {id:'system', label:'SYSTEM', icon:'⚙', roles:['ENGINEER'],`);
w(`   items:[`);
w(`     {id:'orchestrator',label:'Orchestrator',icon:'⬡',desc:'Service mesh & elastic scaling',   roles:['ENGINEER']},`);
w(`     {id:'api',     label:'API Explorer',  icon:'{}', desc:'REST API reference & test',         roles:['ENGINEER']},`);
w(`     {id:'preflight',label:'Pre-Flight',   icon:'✓',  desc:'System readiness checks',           roles:['ENGINEER','OPERATOR']},`);
w(`     {id:'compat',  label:'Compatibility', icon:'⊞',  desc:'Equipment compatibility matrix',    roles:['ENGINEER','OPERATOR']},`);
w(`   ]},`);
w(`  {id:'training', label:'TRAINING', icon:'📚', roles:['ENGINEER','OPERATOR','TRAINER','VIEWER'],`);
w(`   items:[`);
w(`     {id:'training',label:'NEXUS Academy', icon:'🎓', desc:'Interactive training modules',      roles:['ENGINEER','OPERATOR','TRAINER','VIEWER']},`);
w(`   ]}`);
w(`];`);
w(``);
w(`var _activeView = 'live';`);
w(``);
w(`function _buildNav(){`);
w(`  var nav = document.getElementById('tb-nav');`);
w(`  nav.innerHTML = '';`);
w(`  NAV_GROUPS.forEach(function(grp){`);
w(`    // Check if role can see this group at all`);
w(`    if(grp.roles.indexOf(ROLE)<0) return;`);
w(`    var visItems = grp.items.filter(function(it){return it.roles.indexOf(ROLE)>=0;});`);
w(`    if(!visItems.length) return;`);
w(`    var hasActive = visItems.some(function(it){return it.id===_activeView;});`);
w(`    var grpEl = document.createElement('div');`);
w(`    grpEl.className = 'nav-group';`);
w(`    grpEl.innerHTML =`);
w(`      '<button class="nav-group-btn'+(hasActive?' has-active':'')+'" onclick="toggleNavGroup(this)">'+`);
w(`        grp.icon+' '+grp.label+' <span class="arrow">▾</span>'+`);
w(`      '</button>'+`);
w(`      '<div class="nav-dropdown">'+`);
w(`        visItems.map(function(it){`);
w(`          var isActive = it.id===_activeView;`);
w(`          return '<div class="nav-dd-item'+(isActive?' active':'')+'" onclick="showView(\''+it.id+'\');closeAllDropdowns()">'+`);
w(`            '<span class="nav-dd-icon">'+it.icon+'</span>'+`);
w(`            '<div><div class="nav-dd-label">'+it.label+'</div>'+`);
w(`            '<div class="nav-dd-desc">'+it.desc+'</div></div>'+`);
w(`          '</div>';`);
w(`        }).join('')+`);
w(`      '</div>';`);
w(`    nav.appendChild(grpEl);`);
w(`  });`);
w(`}`);
w(``);
w(`function toggleNavGroup(btn){`);
w(`  var grp = btn.parentElement;`);
w(`  var wasOpen = grp.classList.contains('open');`);
w(`  closeAllDropdowns();`);
w(`  if(!wasOpen){grp.classList.add('open');btn.classList.add('open');}`);
w(`}`);
w(`function closeAllDropdowns(){`);
w(`  document.querySelectorAll('.nav-group').forEach(function(g){g.classList.remove('open');});`);
w(`  document.querySelectorAll('.nav-group-btn').forEach(function(b){b.classList.remove('open');});`);
w(`}`);
w(`document.addEventListener('click',function(e){`);
w(`  if(!e.target.closest('.nav-group')) closeAllDropdowns();`);
w(`});`);
w(``);
w(`function showView(id){`);
w(`  document.querySelectorAll('.view').forEach(function(v){v.classList.remove('on');});`);
w(`  var v=document.getElementById('view-'+id);`);
w(`  if(v){v.classList.add('on','anim');}`);
w(`  _activeView=id;`);
w(`  _buildNav();`);
w(`}`);

w(``);
w(`// ─── SOURCES ─────────────────────────────────────────────────────────────────`);
w(`var SOURCES = [`);
w(`  {id:'CAM-01',label:'CAM 01',type:'camera',loc:'Floor A',status:'pgm',format:'1080i50'},`);
w(`  {id:'CAM-02',label:'CAM 02',type:'camera',loc:'Floor A',status:'pvw',format:'1080i50'},`);
w(`  {id:'CAM-03',label:'CAM 03',type:'camera',loc:'Floor B',status:'ok',format:'1080i50'},`);
w(`  {id:'CAM-04',label:'CAM 04',type:'camera',loc:'Floor B',status:'ok',format:'1080i50'},`);
w(`  {id:'CAM-05',label:'CAM 05',type:'camera',loc:'Crane',status:'ok',format:'1080p50'},`);
w(`  {id:'CAM-06',label:'CAM 06',type:'camera',loc:'Jib',status:'ok',format:'1080p50'},`);
w(`  {id:'CAM-07',label:'CAM 07',type:'camera',loc:'RF-A',status:'ok',format:'1080i50'},`);
w(`  {id:'CAM-08',label:'CAM 08',type:'camera',loc:'RF-B',status:'ok',format:'1080i50'},`);
w(`  {id:'GFX-01',label:'GFX 01',type:'graphics',loc:'Viz 1',status:'ok',format:'1080i50'},`);
w(`  {id:'GFX-02',label:'GFX 02',type:'graphics',loc:'Viz 2',status:'ok',format:'1080i50'},`);
w(`  {id:'VTR-01',label:'VTR 01',type:'replay',loc:'EVS 1',status:'ok',format:'1080i50'},`);
w(`  {id:'VTR-02',label:'VTR 02',type:'replay',loc:'EVS 2',status:'ok',format:'1080i50'},`);
w(`  {id:'VTR-03',label:'VTR 03',type:'replay',loc:'EVS 3',status:'ok',format:'1080i50'},`);
w(`  {id:'REM-01',label:'REM 01',type:'remote',loc:'SRT In',status:'ok',format:'H.264'},`);
w(`  {id:'REM-02',label:'REM 02',type:'remote',loc:'SRT In',status:'warn',format:'H.265'},`);
w(`  {id:'REM-03',label:'REM 03',type:'remote',loc:'Bonded',status:'ok',format:'H.264'},`);
w(`  {id:'NET-01',label:'NET 01',type:'network',loc:'Sat Feed',status:'ok',format:'MPEG-2'},`);
w(`  {id:'NET-02',label:'NET 02',type:'network',loc:'Fiber',status:'ok',format:'ST2110'},`);
w(`  {id:'TST-01',label:'BARS',type:'test',loc:'Internal',status:'ok',format:'1080i50'},`);
w(`  {id:'TST-02',label:'BLACK',type:'test',loc:'Internal',status:'ok',format:'1080i50'},`);
w(`  {id:'CLN-01',label:'CLEAN',type:'clean',loc:'ME1 Out',status:'pgm',format:'1080i50'},`);
w(`  {id:'CLN-02',label:'CLEAN 2',type:'clean',loc:'ME2 Out',status:'ok',format:'1080i50'},`);
w(`  {id:'AUX-01',label:'AUX 01',type:'aux',loc:'Aux',status:'ok',format:'1080i50'},`);
w(`  {id:'AUX-02',label:'AUX 02',type:'aux',loc:'Aux',status:'ok',format:'1080i50'}`);
w(`];`);
w(``);
w(`// ─── SWITCHER STATE ───────────────────────────────────────────────────────────`);
w(`var SW = {`);
w(`  me: [`);
w(`    {name:'ME 1',pgm:'CAM-01',pvw:'CAM-02',trans:0,running:false,rate:25,type:'MIX',`);
w(`     keys:[`);
w(`       {n:1,type:'LUM',src:'GFX-01',fill:'GFX-01',on:false,upstream:true},`);
w(`       {n:2,type:'CHR',src:'GFX-02',fill:'GFX-02',on:false,upstream:true},`);
w(`       {n:3,type:'PAT',src:'TST-01',fill:'TST-01',on:false,upstream:true},`);
w(`       {n:4,type:'DVE',src:'CAM-03',fill:'CAM-03',on:false,upstream:false},`);
w(`       {n:5,type:'LUM',src:'CLN-01',fill:'CLN-01',on:false,upstream:false},`);
w(`       {n:6,type:'CHR',src:'GFX-01',fill:'GFX-01',on:false,upstream:false}`);
w(`     ]},`);
w(`    {name:'ME 2',pgm:'CAM-03',pvw:'VTR-01',trans:0,running:false,rate:25,type:'MIX',`);
w(`     keys:[`);
w(`       {n:1,type:'LUM',src:'GFX-01',fill:'GFX-01',on:false,upstream:true},`);
w(`       {n:2,type:'CHR',src:'GFX-02',fill:'GFX-02',on:false,upstream:true},`);
w(`       {n:3,type:'PAT',src:'TST-01',fill:'TST-01',on:false,upstream:true},`);
w(`       {n:4,type:'DVE',src:'CAM-05',fill:'CAM-05',on:false,upstream:false},`);
w(`       {n:5,type:'LUM',src:'CLN-02',fill:'CLN-02',on:false,upstream:false},`);
w(`       {n:6,type:'CHR',src:'GFX-02',fill:'GFX-02',on:false,upstream:false}`);
w(`     ]},`);
w(`    {name:'ME 3',pgm:'CLN-01',pvw:'CAM-05',trans:0,running:false,rate:25,type:'CUT',`);
w(`     keys:[`);
w(`       {n:1,type:'LUM',src:'GFX-01',fill:'GFX-01',on:false,upstream:true},`);
w(`       {n:2,type:'CHR',src:'GFX-02',fill:'GFX-02',on:false,upstream:true},`);
w(`       {n:3,type:'PAT',src:'TST-01',fill:'TST-01',on:false,upstream:true},`);
w(`       {n:4,type:'DVE',src:'CAM-06',fill:'CAM-06',on:false,upstream:false},`);
w(`       {n:5,type:'LUM',src:'CLN-01',fill:'CLN-01',on:false,upstream:false},`);
w(`       {n:6,type:'CHR',src:'GFX-01',fill:'GFX-01',on:false,upstream:false}`);
w(`     ]}`);
w(`  ]`);
w(`};`);
w(``);
w(`// ─── ROUTER STATE ─────────────────────────────────────────────────────────────`);
w(`var ROUTER = {};`);
w(`(function(){`);
w(`  var dests=['PGM-A','PGM-B','PVW-A','PVW-B','MON-1','MON-2','MON-3','MON-4',`);
w(`             'REC-1','REC-2','STR-1','STR-2','AUX-1','AUX-2','AUX-3','AUX-4'];`);
w(`  var srcs=['CAM-01','CAM-02','CAM-03','CAM-04','CAM-05','CAM-06','GFX-01','GFX-02',`);
w(`            'VTR-01','VTR-02','REM-01','NET-01','TST-01','CLN-01','CLN-02','TST-02'];`);
w(`  dests.forEach(function(d,i){ROUTER[d]=srcs[i%srcs.length];});`);
w(`})();`);
w(``);
w(`// ─── MOSAIC STATE ─────────────────────────────────────────────────────────────`);
w(`var MOSAIC = {`);
w(`  layout:'3x3',`);
w(`  tiles:[`);
w(`    {src:'CAM-01'},{src:'CAM-02'},{src:'CAM-03'},`);
w(`    {src:'CAM-04'},{src:'CAM-05'},{src:'GFX-01'},`);
w(`    {src:'VTR-01'},{src:'REM-01'},{src:'CLN-01'}`);
w(`  ],`);
w(`  presets:[],`);
w(`  layouts:{'2x2':{cols:2,count:4},'3x3':{cols:3,count:9},'4x4':{cols:4,count:16},'1+5':{cols:3,count:6},'2+8':{cols:4,count:10}}`);
w(`};`);
w(``);
w(`// ─── ALARMS ───────────────────────────────────────────────────────────────────`);
w(`var ALARMS = [];`);
w(`function addAlarm(sev,msg){`);
w(`  ALARMS.unshift({sev:sev,msg:msg,time:p2(_th)+':'+p2(_tm)+':'+p2(_ts)});`);
w(`  if(ALARMS.length>200) ALARMS.pop();`);
w(`  _updateAlarmBar();`);
w(`  dbSave('alarms',ALARMS.slice(0,50));`);
w(`}`);
w(`function _updateAlarmBar(){`);
w(`  var cnt=ALARMS.filter(function(a){return a.sev==='crit'||a.sev==='warn';}).length;`);
w(`  var el=document.getElementById('sb-alm'),tx=document.getElementById('sb-alm-txt');`);
w(`  if(el&&tx){if(cnt>0){el.style.display='flex';tx.textContent='⚠ '+cnt+' ALARM'+(cnt>1?'S':'');}else el.style.display='none';}`);
w(`}`);
w(``);
w(`// ─── TOAST ────────────────────────────────────────────────────────────────────`);
w(`function toast(type,title,body){`);
w(`  var wrap=document.getElementById('toast-wrap');`);
w(`  var el=document.createElement('div');`);
w(`  el.className='toast toast-'+type;`);
w(`  el.innerHTML='<div class="toast-title">'+(type==='deny'?'⛔ ':type==='ok'?'✓ ':type==='warn'?'⚠ ':'ℹ ')+title+'</div>'+(body?'<div class="toast-body">'+body+'</div>':'');`);
w(`  wrap.appendChild(el);`);
w(`  setTimeout(function(){if(el.parentNode)el.remove();},3500);`);
w(`}`);
w(``);
w(`// ─── DATABASE (localStorage) ──────────────────────────────────────────────────`);
w(`var DB = {};`);
w(`function dbLoad(){`);
w(`  try{`);
w(`    var raw=localStorage.getItem('nexus_v5_db');`);
w(`    if(raw) DB=JSON.parse(raw);`);
w(`  }catch(e){DB={};}`);
w(`}`);
w(`function dbSave(key,val){`);
w(`  try{`);
w(`    DB[key]=val;`);
w(`    localStorage.setItem('nexus_v5_db',JSON.stringify(DB));`);
w(`  }catch(e){}`);
w(`}`);
w(`function dbGet(key,def){return DB[key]!==undefined?DB[key]:def;}`);
w(`function dbClear(){try{localStorage.removeItem('nexus_v5_db');DB={};}catch(e){}}`);
w(``);
w(`// ─── TIMECODE ─────────────────────────────────────────────────────────────────`);
w(`function _startTC(){`);
w(`  _ivs.push(setInterval(function(){`);
w(`    _tf++;if(_tf>=25){_tf=0;_ts++;}if(_ts>=60){_ts=0;_tm++;}if(_tm>=60){_tm=0;_th++;}`);
w(`    var tc=p2(_th)+':'+p2(_tm)+':'+p2(_ts)+':'+p2(_tf);`);
w(`    var el=document.getElementById('sb-tc');if(el)el.textContent=tc;`);
w(`    var off=(Math.random()*2.4-1.2).toFixed(1);`);
w(`    var pe=document.getElementById('sb-ptp');`);
w(`    if(pe){pe.textContent='PTP '+(off>=0?'+':'')+off+'ns';pe.style.color=Math.abs(off)>2?'var(--warn)':'var(--acc)';}`);
w(`  },40));`);
w(`}`);
w(``);
w(`// ─── LOGIN ────────────────────────────────────────────────────────────────────`);
w(`var _selRole='ENGINEER';`);
w(`function selRole(el){`);
w(`  document.querySelectorAll('.lg-role-card').forEach(function(c){c.classList.remove('sel');});`);
w(`  el.classList.add('sel');`);
w(`  _selRole=el.dataset.role;`);
w(`}`);
w(`function doLogin(){`);
w(`  var pw=document.getElementById('lg-pw').value;`);
w(`  var err=document.getElementById('lg-err');`);
w(`  if(pw!==PW){err.style.display='block';return;}`);
w(`  err.style.display='none';`);
w(`  ROLE=_selRole;`);
w(`  document.getElementById('login').style.display='none';`);
w(`  document.getElementById('app').style.display='flex';`);
w(`  document.getElementById('tb-role').textContent=ROLE;`);
w(`  document.getElementById('sb-role').textContent=ROLE;`);
w(`  document.getElementById('tb-role').className='lbl role-'+ROLE.toLowerCase().substring(0,3);`);
w(`  dbLoad();`);
w(`  _buildNav();`);
w(`  _startTC();`);
w(`  _initAll();`);
w(`  showView('live');`);
w(`}`);
w(``);
w(`// ─── SWITCH USER ──────────────────────────────────────────────────────────────`);
w(`function openSwitchUser(){`);
w(`  var existing=document.getElementById('switch-modal');`);
w(`  if(existing){existing.remove();return;}`);
w(`  var m=document.createElement('div');`);
w(`  m.id='switch-modal';m.className='modal-bg';`);
w(`  m.innerHTML='<div class="modal-box">'+`);
w(`    '<div class="modal-title">⇄ Switch Role</div>'+`);
w(`    '<div class="lg-err" id="sw-err" style="display:none">⚠ INCORRECT ACCESS CODE</div>'+`);
w(`    '<label class="lg-lbl">Access Code</label>'+`);
w(`    '<input class="lg-inp" type="password" id="sw-pw" placeholder="••••••••" onkeydown="if(event.key===\'Enter\')_doSwitch()">'+`);
w(`    '<label class="lg-lbl" style="margin-bottom:10px">New Role</label>'+`);
w(`    '<div class="lg-roles">'+`);
w(`      ['ENGINEER','OPERATOR','TRAINER','VIEWER'].map(function(r){`);
w(`        var icons={ENGINEER:'⚙',OPERATOR:'🎬',TRAINER:'📚',VIEWER:'👁'};`);
w(`        var descs={ENGINEER:'Full system access',OPERATOR:'Production control',TRAINER:'Training & guided',VIEWER:'Monitor only'};`);
w(`        return '<div class="lg-role-card'+(r===ROLE?' sel':'')+'" data-role="'+r+'" onclick="selSwRole(this)">'+`);
w(`          '<div class="rc-name">'+icons[r]+' '+r+'</div>'+`);
w(`          '<div class="rc-desc">'+descs[r]+'</div></div>';`);
w(`      }).join('')+`);
w(`    '</div>'+`);
w(`    '<div style="display:flex;gap:8px;margin-top:8px">'+`);
w(`      '<button class="btn" style="flex:1" onclick="document.getElementById(\'switch-modal\').remove()">CANCEL</button>'+`);
w(`      '<button class="btn btn-acc" style="flex:2" onclick="_doSwitch()">SWITCH ROLE</button>'+`);
w(`    '</div>'+`);
w(`    '<div class="lg-hint">Demo code: nexus2024</div>'+`);
w(`  '</div>';`);
w(`  document.body.appendChild(m);`);
w(`  m.addEventListener('click',function(e){if(e.target===m)m.remove();});`);
w(`  setTimeout(function(){var el=document.getElementById('sw-pw');if(el)el.focus();},50);`);
w(`}`);
w(`var _swRole=null;`);
w(`function selSwRole(el){`);
w(`  document.querySelectorAll('#switch-modal .lg-role-card').forEach(function(c){c.classList.remove('sel');});`);
w(`  el.classList.add('sel');_swRole=el.dataset.role;`);
w(`}`);
w(`function _doSwitch(){`);
w(`  var pw=document.getElementById('sw-pw').value;`);
w(`  var err=document.getElementById('sw-err');`);
w(`  if(pw!==PW){err.style.display='block';return;}`);
w(`  var nr=_swRole||document.querySelector('#switch-modal .lg-role-card.sel');`);
w(`  if(nr&&nr.dataset) nr=nr.dataset.role;`);
w(`  if(!nr){err.style.display='block';return;}`);
w(`  ROLE=nr;`);
w(`  document.getElementById('switch-modal').remove();`);
w(`  document.getElementById('tb-role').textContent=ROLE;`);
w(`  document.getElementById('sb-role').textContent=ROLE;`);
w(`  document.getElementById('tb-role').className='lbl role-'+ROLE.toLowerCase().substring(0,3);`);
w(`  _buildNav();`);
w(`  // Navigate to first allowed view`);
w(`  var allowed=[];`);
w(`  NAV_GROUPS.forEach(function(g){g.items.forEach(function(it){if(it.roles.indexOf(ROLE)>=0)allowed.push(it.id);});});`);
w(`  if(allowed.indexOf(_activeView)<0) showView(allowed[0]||'live');`);
w(`  else _buildNav();`);
w(`  toast('ok','Role Switched','Now operating as '+ROLE);`);
w(`  addAlarm('info','Role switched to '+ROLE);`);
w(`}`);
w(``);
w(`// ─── ENV MODE ─────────────────────────────────────────────────────────────────`);
w(`function setEnvMode(mode){`);
w(`  ENV_MODE=mode;`);
w(`  var el=document.getElementById('tb-env-lbl');if(el)el.textContent=mode;`);
w(`  var sb=document.getElementById('sb-env');if(sb)sb.textContent=mode;`);
w(`  var colors={GROUND:'var(--gold)',CLOUD:'var(--acc)',HYBRID:'var(--pur)'};`);
w(`  if(el)el.style.color=colors[mode]||'var(--acc)';`);
w(`  if(sb)sb.style.color=colors[mode]||'var(--acc)';`);
w(`  dbSave('env_mode',mode);`);
w(`  toast('info','Environment Mode','Switched to '+mode+' workflow');`);
w(`  addAlarm('info','Environment: '+mode);`);
w(`}`);
w(`</script>`);

w(`<script>`);
w(`// ─── INIT ALL ─────────────────────────────────────────────────────────────────`);
w(`function _initAll(){`);
w(`  _initLive();`);
w(`  _initMosaic();`);
w(`  _initSwitcher();`);
w(`  _initRouter();`);
w(`  _initFlow();`);
w(`  _initCloudMCR();`);
w(`  _initSRT();`);
w(`  _initScopes();`);
w(`  _initPTP();`);
w(`  _initNMOS();`);
w(`  _initDevices();`);
w(`  _initAPI();`);
w(`  _initPreflight();`);
w(`  _initRundown();`);
w(`  _initPlayout();`);
w(`  _initOrchestrator();`);
w(`  _initTraining();`);
w(`  _initCompat();`);
w(`  _initNetwork();`);
w(`  _initAutomation();`);
w(`  _initDatabase();`);
w(`  // Restore env mode from DB`);
w(`  var savedEnv=dbGet('env_mode','HYBRID');`);
w(`  setEnvMode(savedEnv);`);
w(`  addAlarm('ok','NEXUS v5 initialized — all systems nominal');`);
w(`  addAlarm('info','PTP locked ±1.2ns — SMPTE ST 2059-2');`);
w(`  addAlarm('warn','Viz Engine 2: CPU 88% — monitor');`);
w(`  _wsConnect();`);
w(`}`);
w(``);
w(`// ─── WEBSOCKET ────────────────────────────────────────────────────────────────`);
w(`var _ws=null,_wsReconnCount=0,_wsConnected=false;`);
w(`var _srcMap={'1':'CAM-01','2':'CAM-02','3':'CAM-03','4':'CAM-04','5':'CAM-05','6':'CAM-06',`);
w(`  '7':'CAM-07','8':'CAM-08','9':'GFX-01','10':'GFX-02','11':'VTR-01','12':'VTR-02',`);
w(`  '13':'VTR-03','14':'REM-01','15':'REM-02','16':'REM-03','20':'TST-01','21':'TST-02'};`);