apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-broadcast

resources:
  - ../../base

images:
  - name: nexus-api
    newName: ghcr.io/nexus-broadcast/nexus-v4/api
    newTag: latest
  - name: nexus-switcher
    newName: ghcr.io/nexus-broadcast/nexus-v4/switcher
    newTag: latest
  - name: nexus-router
    newName: ghcr.io/nexus-broadcast/nexus-v4/router
    newTag: latest
  - name: nexus-nmos
    newName: ghcr.io/nexus-broadcast/nexus-v4/nmos
    newTag: latest

replicas:
  - name: nexus-api
    count: 5

configMapGenerator:
  - name: nexus-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
